### DISCUSSION TITLE
ignore_checks for specific templates in config

### DISCUSSION THREAD

**Discussion by marais-vzc** [aws-cloudformation/cfn-lint#3264] [Q&A] [answered]
We make use of the .cfnlintrc config in our repositories.

What we want to achieve is to `ignore_checks` for specific templates. The reason is that an error might be raised for template a, but template B we want to ignore that error as it is a false positive.

Take the following snippet

```
Conditions:
  CreateSubnetMappings:
    !Not [!Equals [!Ref AllocationId, '']]
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: !Ref Scheme
      SubnetMappings:
        !If
          - CreateSubnetMappings
          -
            - 
              AllocationId: !Ref AllocationId
              SubnetId: !Ref SubnetId
          - !Ref "AWS::NoValue"
      Subnets: 
        - !If [CreateSubnetMappings, !Ref "AWS::NoValue", !Ref SubnetId]
```
We now see `E2523 Only one of [SubnetMappings, Subnets] should be specified when condition "CreateSubnetMappings" is True`, but the condition `CreateSubnetMappings` will ensure that either one of `SubnetMappings` or `Subnets` will be specified, not both.

We now want to disable rule E2523 in this template, but still need it elsewhere.

How do we do this? Or how do I change the template to silence this error?
