### DISCUSSION TITLE
Optional pre-processing

### DISCUSSION THREAD

**Discussion by gbudge** [aws-cloudformation/cfn-lint#3793] [Ideas]
Hi All,

The issue I described in [this thread](https://github.com/aws-cloudformation/cfn-lint/discussions/3093) is really frustrating me, so I have had to resort to manually changing the `TemplateURL` temporarily to a local relative path, run cfn-lint and then reverting it back to an S3 URL.

Example:
```yaml
  ServiceCatalogue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/${BucketName}/sc-stack.yml"
      # TemplateURL: "./sc-stack.yml"
      Parameters:
        PortfolioId: !Ref PortfolioId
```

I do have a script that does provide some automation but it's a bit cumbersome.

Whilst I can improve it the main issue I have is that I'd have to figure out the inventory of files intended to be scanned before executing cfn-lint, depending on what the VS Code Extension passes in (single file), what the user passes as a parameter via the command line (could be many files) and also what's in the cfnlint rc file.

It's doable but it got me wondering why cfn-lint cannot be enhanced to support an experimental feature to pre-process/pre-render the files before they're scanned, via a user supplied Python script?

There'd have to be caveats of course..

- The feature is experimental (at least initially).
- The script would need to conform to some to-be-determined strict standard, input and output values/codes.
- cfn-lint would need to temporarily copy the files being scanned to a temporary location before running the pre-rendering script (so the original files aren't changed).
- etc.

Example:
```shell
cfn-lint <cfn-lint-options> --renderer <script>
```

Anyway, food for thought .. I'd imagine there'd be other worthwhile use cases.
