### ISSUE TITLE
Disable rules with inline comments

### ISSUE THREAD

**Issue by sd65** [aws-cloudformation/cfn-lint#113]
Hi all,

As a linter used in IDEs, the possibility to add inline comments to ignore a line would be useful.
I think [this](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) could inpire us.

What do you think?

**Comment by kddejong** [comment]
So far we have tried to treat json and yaml files the same but we wouldn't be able to do that in this case.

Technically I think this is possible.  We would have to rework the yaml parser to store comments into an object we can parse and look for certain patterns, etc, etc.

It would be a little inefficient but we would have to capture all the failures and then see if each error was inside the enable/disable blocks. 

Let me think on this... I'm working through a few more issues before I would be able to get to this one.

**Comment by sd65** [comment]
I see your point. I like your idea of capturing all errors and checking then if we can ignore them.

Furthermore, a first step would be to simply check for end of the line ignore rules comment. Then, the support for ignore block could come.

**Comment by adamchainz** [comment]
You can disable rules with the currently undocumented Metadata section, [example in tests](https://github.com/awslabs/cfn-python-lint/blob/7eb6fd3ba1fdccf09326d89e73a22924f99de21d/test/fixtures/templates/good/core/config_parameters.yaml).

**Comment by ossek** [comment]
Is it possible to disable specific instances of check? E.g., since transform include is not supported (https://github.com/awslabs/cfn-python-lint/issues/15#issuecomment-383575448) it would be nice to disable the type of output below (on a template that passes aws cloudformation validate-template). I still would like to see other instances of E3001 though.

E3001 Type not defined for resource Fn::Transform
shared_nested_stack_client/parent_template.yaml:18:3

E3006 Resources Fn::Transform has invalid name.  Name has to be alphanumeric.
shared_nested_stack_client/parent_template.yaml:18:3

E3001 Invalid resource attribute Name for resource Fn::Transform
shared_nested_stack_client/parent_template.yaml:19:5

E3001 Invalid resource attribute Parameters for resource Fn::Transform
shared_nested_stack_client/parent_template.yaml:20:5

**Comment by cmmeyer** [comment]
Right now you can only turn on and off rules.  But for your use case, it seems like it might make more sense for us to enhance the linter to lint around Fn::Transform?  I can add that as an enhancement.

**Comment by ossek** [comment]
Excellent, thanks @cmmeyer, let me know if I can provide any other information, and if you could add a link here for the issue once created, much appreciated.

**Comment by chizou** [comment]
I would like to chime in that I would also prefer to disable specific instances of a check.

E2520 is checking for mutual exclusions which is fine except when I'm also checking it in my template. 

The below resource will throw E2520 because I'm specifying `MasterUserPassword`/`MasterUsername` with `SnapshotIdentifier`
```
  AuroraCluster:
    Properties:
      BackupRetentionPeriod: !Ref 'BackupRetention'
      DBClusterIdentifier: !Ref 'DBClusterIdentifier'
      DBClusterParameterGroupName: default.aurora-postgresql10
      DBSubnetGroupName: !ImportValue
        Fn::Sub: ${NetworkName}-network-dbsubnet
      DatabaseName: !If
        - UseSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'DatabaseName'
      DeletionProtection: 'true'
      Engine: !Ref 'DBEngine'
      EngineVersion: !Ref 'DBEngineVersion'
      KmsKeyId: !Ref 'KmsKeyId'
      MasterUserPassword: !If
        - UseSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'Password'
      MasterUsername: !If
        - UseSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'Username'
      Port: 5432
      SnapshotIdentifier: !If
        - UseSnapshot
        - !Ref 'ClusterSnapshotIdentifier'
        - !Ref 'AWS::NoValue'
      StorageEncrypted: 'true'
      Tags:
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: Name
          Value: !Ref 'DBClusterIdentifier'
        - Key: POCEmail
          Value: grant.soyka@radiantsolutions.com
        - Key: POCName
          Value: Grant Soyka
        - Key: Project
          Value: !Ref 'ProjectName'
      VpcSecurityGroupIds:
        - !Ref 'DBSecurityGroup'
    Type: AWS::RDS::DBCluster
```
