### ISSUE TITLE
configure_rules doesn't apply in Metadata of a resource

### ISSUE THREAD

**Issue by gergnz** [aws-cloudformation/cfn-lint#1184]
*cfn-lint version: 0.24.8*

I would expect that you can set configure rules the same as you can exclude rules at a resource metadata level.

```
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  asg:
    Metadata:
      cfn-lint:
        config:
          configure_rules:
            E3012:
              strict: 'False'
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: i-1234567890
      MinSize: 0
      MaxSize: 10
```
results in:
```
E3012 Property Resources/asg/Properties/MinSize should be of type String
z.yml:14:7

E3012 Property Resources/asg/Properties/MaxSize should be of type String
z.yml:15:7
```

Using ignore_checks for the resource works:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  asg:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3012
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: i-1234567890
      MinSize: 0
      MaxSize: 10
```

But moving the config to the top level works but is too permissive (applying to the whole template):
```
---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  cfn-lint:
    config:
      configure_rules:
        E3012:
          strict: 'False'
Resources:
  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: i-1234567890
      MinSize: 0
      MaxSize: 10
```
