### ISSUE TITLE
Add check for missing !Ref in condition

### ISSUE THREAD

**Issue by kylelaker** [aws-cloudformation/cfn-lint#1267]
*cfn-lint version: (`cfn-lint --version`)*: cfn-lint 0.26.0

*Description of issue.*

It'd be helpful if cfn-lint had a check when parameter names or psuedo-parameters are used in conditions without a `!Ref` much like it checks for strings with `${PARAMETER}` without a `!Sub`. This would prevent accidental comparisons with a string literal. It might also be helpful to check for conditions that will always evaluate to true/false.

For example:

```yaml
---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  MyTestParameter:
    Type: String
    Default: ""

Conditions:
    CreateFooResource: !Not [!Equals [MyTestParameter, ""]]

Resources:
  Foo:
    Type: AWS::IAM::User
    Condition: CreateFooResource
    Properties: {}
```

It would be helpful to get a warning that `CreateFooResource` always evaluates to true or that it's comparing two string literals, one of which is a parameter name.
