### ISSUE TITLE
Detect with a linter if the argument is not an ARN in AWS::CodePipeline::Pipeline

### ISSUE THREAD

**Issue by mariano-calandra-xp** [aws-cloudformation/cfn-lint#1393]
*cfn-lint version: cfn-lint 0.28.2*

*Description of issue.*
I was having really hard time debugging an error with CloudFormation syntax: when the CloudFormation try to deploy the stack it gave me an error like: "user:xyz/CloudFormationRole is not authorized to iam:passRole on resource".

In the first time I was going crazy searching for the error in IAM role, but after a stroll I realized that the error was here `RoleArn: !Ref CloudFormationRole`. 

```yml
- Name: Deploy
            Actions:
              - Name: CreateChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                InputArtifacts:
                  - Name: BuildArtifact
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                  RoleArn: !Ref CloudFormationRole # ERROR HERE (next line is correct)
                  # RoleArn: !GetAtt CloudFormationRole.Arn
                  StackName: lambda-deploy-stack
                  TemplatePath: "BuildArtifact::package.yaml"
                  ChangeSetName: lambda-deploy-changeset
                RunOrder: 1
```

Would be useful if the linter could validate this type of error upfront. 
Here is an expanded version of YML https://gist.github.com/mariano-calandra-xp/8cb92afdd379aeed09a5df1cd2582c65
