### ISSUE TITLE
AWS::Serverless::Function.EventInvokeConfig.MaximumRetryAttempts constraints not enforced

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cfn-lint#1926]
*cfn-lint version: 0.46.0*

*Description of issue.*

```yaml
  RelayFunction:
    Type: AWS::Serverless::Function
    Properties:
      EventInvokeConfig:
        MaximumRetryAttempts: 5
```

`cfn-lint` doesn't complain about this setup, but deploying it results in:

> 1 validation error detected: Value '5' at 'maximumRetryAttempts' failed to satisfy constraint: Member  must have value less than or equal to 2

**Comment by kddejong** [comment]
@farski I believe `MaximumRetryAttempts` is converted to `AWS::Lambda::EventSourceMapping` Looks like that [limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumretryattempts) is pretty high so maybe the limit is conditional based on the event source its mapped to.  What is your event source?

**Comment by farski** [comment]
```yaml
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Destination: !Ref RelayFunctionFailureSnsTopic
            Type: SNS
        MaximumRetryAttempts: 2
```
