### ISSUE TITLE
 Is it possible to have a Condition inside the !Equals

### ISSUE THREAD

**Issue by biohazd** [aws-cloudformation/cfn-lint#2019]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.46.0

*Description of issue.*
Is it possibe to have a Condition inside the !Equals ?

Example
```yaml
Conditions:
   enableLogging: !Not [!Equals [!Join ['', !Ref EnableCloudwatchLogsExports], '']]
 
   enableLoggingEngine: !And
       - !Equals [ !Condition enableLogging, 'true' ]
       - !Equals [ !Ref Engine, 'aurora' ]
```

`[cfn-lint] E8003: Fn::Equals element must be a supported function (Ref, Fn::FindInMap, Fn::Sub, Fn::Join, Fn::Select, Fn::Split)`

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
