### ISSUE TITLE
E3002 - ERROR on Kinesis Firehose

### ISSUE THREAD

**Issue by azaa1** [aws-cloudformation/cfn-lint#2020]
*cfn-lint version: (`cfn-lint --version`)*
0.44.2
*Description of issue.*
Getting E3002 on Kinesis Firehose when ```DeliveryStreamEncryptionConfigurationInput``` property is added to template. 

Please provide as much information as possible:
E3002 happens only if I define "DeliveryStreamEncryptionConfigurationInput", have tried testing the template without running cfn-lint, works just fine. 

* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  
```yaml
  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamEncryptionConfigurationInput:
        KeyARN: !GetAtt LoggingKey.Arn
        KeyType: CUSTOMER_MANAGED_CMK
```

  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
