### ISSUE TITLE
E3031: ManagedPolicyArns contains invalid characters... for a valid managed Policy

### ISSUE THREAD

**Issue by dfuentes77** [aws-cloudformation/cfn-lint#2022]
*cfn-lint version: 0.49.2*

I'm getting this cfn-lint error for a sam-cli template:
```
[cfn-lint] E3031: ManagedPolicyArns contains invalid characters (Pattern: arn:(aws[a-zA-Z-]*)?:iam::(\d{12}|aws):policy/[a-zA-Z_0-9+=,.@\-_/]+) at Resources/MyFunctionRole/Properties/ManagedPolicyArns/4
```

specifically for the `CloudWatchLambdaInsightsExecutionRolePolicy` policy:
```yaml
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
    ...
      Policies:
        - AWSLambdaRole       # AWS Managed Role to allow Lambda invokation permissions
        - CloudWatchLambdaInsightsExecutionRolePolicy   # Lambda Insights
```

but that error is not applicable since this syntax works and is officially supported via the documentation:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-policies

where it states:
`This property accepts a single string or a list of strings, and can be the name of AWS managed policies or...`
