### ISSUE TITLE
Unknown CloudFormation resource type: AWS::Chatbot::SlackChannelConfiguration

### ISSUE THREAD

**Issue by RobertoTorino** [aws-cloudformation/cfn-lint#2025]
*cfn-lint version: (0.49.2)*

*Description of issue.*

AWS::Chatbot::SlackChannelConfiguration' is not recognized as a valid resource type.

* CloudFormation sample that generated the issue:
```yaml
SlackChannelConfig:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub "{${Environment}-securityhub-notifications"
      IamRoleArn: !GetAtt ChatBotManageIAMRole.Arn
      LoggingLevel: "ERROR"
      SlackChannelId: !Split [ ",", !Sub "${SlackChannelId}" ]
      SlackWorkspaceId: !Ref SlackWorkSpaceId
      SnsTopicArns:
        - !Ref SecurityHubSNSTopic
```
*Official documentation*
[AWS::Chatbot::SlackChannelConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html)
