### ISSUE TITLE
Condition exclusively used together with Fn::If in a SAM resource reported as unused

### ISSUE THREAD

**Issue by FlorianSW** [aws-cloudformation/cfn-lint#2038]
*cfn-lint version: (`cfn-lint --version`)*
0.50.0

*Description of issue.*
First of all: I'm not sure, if I should file this issue against cfn-lint or the sam-cli tbh. If you think it is more an issue of sam, I"ll can close this issue and go down this road :)

I've declared a condition (see template for a simplified example), which I use exclusively in a resource of type `AWS::Serverless::Function` (enabling or disabling a specific events rule basically, does, however, not really matter here). When I lint this template, I get the error message, that the defined condition is unused, even given it is used in the SAM resource.

Using `cfn-lint --info`, the resulted template still declares the condition, however, it is obviously not used anymore, as sam converted the Events properties to their own resources, which do not use the condition anymore.

When using the same construct (Fn::If + Condition) in a CFN resource, cfn-lint runs completely fine.

Please provide as much information as possible:
**Error message**:
`W8001 Condition WithCondition not used`

**Template to reproduce**:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Conditions:
  WithCondition: !Equals [ !Ref ParamTest, 'true' ]

Parameters:
  ParamTest:
    Type: String
    Default: false
    AllowedValues: [ true, false ]

Resources:
  BackgroundTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: out/
      Handler: main
      Runtime: go1.x
      Events:
        Timed:
          Type: Schedule
          Properties:
            Schedule: rate(100 days)
            Enabled: !If [ WithCondition, true, false ]
      Tracing: 'Active'
```

**Example template which does not fail (using CFN resource instead of AM)**:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Conditions:
  WithCondition: !Equals [ !Ref ParamTest, 'true' ]

Parameters:
  ParamTest:
    Type: String
    Default: false
    AllowedValues: [ true, false ]

Resources:
  RecordServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: !If [ WithCondition, true, false ]
```
