### ISSUE TITLE
Pre-defined and Named Elastic Beanstalk Resources Undetected

### ISSUE THREAD

**Issue by jaradc** [aws-cloudformation/cfn-lint#2075]
**cfn-lint version**: cfn-lint 0.52.0

**Description**
Elastic Beanstalk has [pre-defined named resources](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-format-resources-eb.html). cfn-lint doesn't appear to be able to detect this.

**Code Example**

```
Resources:
  AWSEBV2LoadBalancerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      Port: 80
      Protocol: HTTP
      LoadBalancerArn:
        Ref: AWSEBV2LoadBalancer
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: AWSEBV2LoadBalancerTargetGroup
```

**Template Linting Issue**
In VS Code, I see red squigglies under `LoadBalancerArn` and `TargetGroupArn` because I guess cfn-lint doesn't know that these are resources that Elastic Beanstalk creates:

```
[cfn-lint] E1012: Ref AWSEBV2LoadBalancer not found as a resource or parameter
[cfn-lint] E1012: Ref AWSEBV2LoadBalancerTargetGroup not found as a resource or parameter
```
