### ISSUE TITLE
Junit format output is blank if E0000 is found

### ISSUE THREAD

**Issue by JamieMcKernanKaizen** [aws-cloudformation/cfn-lint#2085]
*cfn-lint version: 0.52.0*

If there is an E0000 error, the junit output format does not output anything.

Here is a minimal template that can be used to recreate the issue:
```
AWSTemplateFormatVersion:'2010-09-09'
Resources:
  TempNullResource:
    Type: 'Custom::NullResource'
```

The error is the missing space between `:` and `'` on the first line. If you run with `--format junit` you will get a blank output. If you add the space back (removing the error) you will see that the junit output has everything present. The junit output works fine with other errors, but if there is an E0000 then the output is blank. This has been tried with python 3.8.6.
