### ISSUE TITLE
AWS::KMS::Alias.TargetKeyId does not support AWS::KMS::ReplicaKey

### ISSUE THREAD

**Issue by ChrisRut** [aws-cloudformation/cfn-lint#2107]
*cfn-lint version: **0.53.0***

*Description of issue.*

AWS::KMS::Alias.TargetKeyId does not support [AWS::KMS::ReplicaKey](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-replicakey.html#cfn-kms-replicakey-keypolicy) resources.

Example test.yaml:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates KMS Resources
Resources:
  ReplicaCMK:
    Type: AWS::KMS::ReplicaKey
    Properties:
      PrimaryKeyArn: "arn:aws:kms:us-east-1:123456789012:key/1234a56b-78c9-01d2-efg3-4h5ijk6l78mn"
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: '*'
  ReplicaCMKAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/test
      TargetKeyId: !Ref ReplicaCMK
```

Example cfn-lint run:
```
$ cfn-lint test.yaml                    
E3008 Property "TargetKeyId" can Ref to resources of types [AWS::KMS::Key] at Resources/ReplicaCMKAlias/Properties/TargetKeyId/Ref
test.yaml:23:7
```

See also: https://github.com/aws-cloudformation/cfn-lint/blob/3d30463ec1cf3eca5141230729ab33070aa7b753/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L234-L246

**Comment by ChrisRut** [comment]
To work-around this issue we're currently using:
```
  ReplicaCMKAlias:
    Type: AWS::KMS::Alias
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3008  # See: https://github.com/aws-cloudformation/cfn-lint/issues/2107
```
