### ISSUE TITLE
Error for template created with AWS SAM

### ISSUE THREAD

**Issue by omer-to** [aws-cloudformation/cfn-lint#2130]
*cfn-lint version: (`cfn-lint --version`)*
`cfn-lint 0.54.2`

*Description of issue.*
Displays an error for a freshly created template using AWS SAM

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!
I just created a new serverless application using AWS SAM.
I ran the following code:
```bash
sam init
```
Selected `AWS Quick Start Templates`, the `Zip` package type, `Node14.0` as the runtime, and `Hello World Example` as the application. But the linter gives the follow error:

```bash
[cfn-lint] E0001: Error transforming template: Resource with id [HelloWorldFunction] is invalid. property Architectures not defined for resource of type AWS::Serverless::Function
```

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by PatMyron** [comment]
I think https://github.com/aws-cloudformation/cfn-lint/pull/2129 will fix this
Try upgrading SAM:
`pip3 install aws-sam-translator --upgrade`

**Comment by PatMyron** [comment]
@omer-to wondering if you might have installed `cfn-lint` through `brew` and that's why it's not picking up `aws-sam-translator-1.39.0` that was installed through `pip`

**Comment by omer-to** [comment]
Hi @PatMyron 
I guess you were right that it was installed with brew.

I ran `brew uninstall cfn-lint` to remove it, and then ran `pip3 install cfn-lint` to install it using `pip`. Here's the output of `pip3 install cfn-lint`:

```bash
Successfully installed cfn-lint-0.54.2 jsonpatch-1.32 jsonpointer-2.1 junit-xml-1.9 networkx-2.6.3 pyyaml-5.4.1
```

And the good news is that the error I mentioned in the original post is gone, thought now I'm facing another one 😃 
Once again this is the template.yaml (auto generated with sam init - helloworld example)
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: hello-world/build/index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
            RequestParameters:
              - method.request.querystring.name:
                  Required: true
                  Caching: false
````

The problem displayed by `cfn-lint`:
```bash
[cfn-lint] E3002: Invalid Property Resources/HelloWorldFunction/Properties/Architectures
```
