### ISSUE TITLE
Defining a Parameter String with Embedded Parameters for later use.

### ISSUE THREAD

**Issue by trbouwens** [aws-cloudformation/cfn-lint#2166]
*cfn-lint version: 0.54.4*

*Description of issue. QUESTION*
I'm trying to reduce duplication in my CloudFormation Template, and want to know if it's possible, as al current attempts have failed me. I'm trying to have a parameter that is a string, which contains embedded variables, then use that string in specific resources (dashboards), where the globally defined parameters can be set, but I can have an ID that is specified via map for each resource.
I have determined that this approach is possible when the string is manually inserted inside the resource with a !Sub, but it appears to not be working if I want to replace those repeated strings with a Parameter String.

Please provide as much information as possible:
Example of my parameter (not remotely exact, but this is the structure) :
```
parameter1:
     Description: "JSON String"
     Type: "String"
     Default: "someParam"

JSON:
     Description: "JSON String"
     Type: "String"
     Default: |
          { "start" : "-value", "widgets"  : [ { "not" : "pasting", "theWhole" : "thing" }, { "something" : " ${parameter1} ", "query" : "filter id like /${p_ID}/ " } ] }
```

Example of resource: 
```
Dashboard1:
     Type: "AWS::CloudWatch::Dashboard"
     Properties: 
          DashboardName: "DB_Name_1"
          DashboardBody: !Sub
               - ${JSON}
               - p_ID : 123456789 

Dashboard2:
     Type: "AWS::CloudWatch::Dashboard"
     Properties: 
          DashboardName: "DB_Name_2"
          DashboardBody: !Sub
               - ${JSON}
               - p_ID : 987654321
```

When I run this initially, I get a E1029 error in `cfn-lint` since there are embedded parameters outside of a !Sub. If I ignore that error in the cli command, it gives me a new one where it says `p_ID`  is not used. Is there a way to work around either of these errors? 

Just to reiterate, if I replace the `DashboardBody` with 
```
!Sub 
     - |
       <the JSON string>
     -  p_ID : <the p_ID for that dashboard>
```
 It works as intended, but since there is a size limit, and the real JSON is very large, I'd like to only have to have it in the document once. 

Thank you,
