### ISSUE TITLE
Object Ownership doesn't allow Value BucketOwnerEnforced

### ISSUE THREAD

**Issue by Jlrine2** [aws-cloudformation/cfn-lint#2191]
cfn-lint version: 0.56.3

When linting a CF temptate containing a bucket with bucket ownership set to `ObjectOwnership: BucketOwnerEnforced` linking fails with the error `
E3030 You must specify a valid value for ObjectOwnership (BucketOwnerEnforced). Valid values are ["ObjectWriter", "BucketOwnerPreferred"]` however Cloudformation allows the value `BucketOwnerEnforced` per the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-ownershipcontrolsrule.html)

sample template 

```yml
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
```

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
