### ISSUE TITLE
E3038 Serverless Transform required even though `Transform: AWS::Serverless-2016-10-31` is written

### ISSUE THREAD

**Issue by iwataka** [aws-cloudformation/cfn-lint#2198]
cfn-lint version: 0.56.3
OS (`uname -a`): Linux DESKTOP-81CDOO5 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

When linting CFn template like the below, even though `Transform: AWS::Serverless-2016-10-31` is written, I got the error `E3038 Serverless Transform required for Type AWS::Serverless::Statemachine for resource Statemachine`

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Statemachine:
    Type: AWS::Serverless::Statemachine
    Properties: {}
```

I did some investigation about cfn-lint code (41d3e74afe076876a25d14c1a29e7579c4ab72a9) and found one possible issue.
I added `print` function to `src/cfnlint/core.py` file like the below and run cfn-lint to the above sample, then got the following output.

```
AWS::Serverless-2016-10-31
[]
```

![image](https://user-images.githubusercontent.com/7800796/148937562-2fa4e049-b789-4891-bd16-59783c8bf14e.png)

I think `runner.transform()` execution causes this error, removing Transform declaration from `runner.cfn.template` before `runner.run()`.

**Comment by kddejong** [comment]
With SAM we validate the template translated by SAM.

The translated template for your example is:
```
{
  "AWSTemplateFormatVersion": null,
  "Resources": {
    "Statemachine": {
      "Properties": {},
      "Type": "AWS::Serverless::Statemachine"
    }
  }
} 
```
The casing on `StateMachine` is wrong so it looks like SAM is skipping it.
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Statemachine:
    Type: AWS::Serverless::StateMachine
    Properties: {}
```
will result in 
```
E0001 Error transforming template: Resource with id [Statemachine] is invalid. Either 'Definition' or 'DefinitionUri' property must be specified.
local/issue/2198.yaml:1:1
```
