### ISSUE TITLE
Rule W3011 says AWS::RDS::DBInstance must have both UpdateReplacePolicy and DeletionPolicy, but AWS::RDS::DBInstance has no such property UpdateReplacePolicy

### ISSUE THREAD

**Issue by DrStrangepork** [aws-cloudformation/cfn-lint#2220]
*cfn-lint version: (`cfn-lint --version`)*
0.58.1

*Description of issue*
Title says it all. You can see from the [AWS::RDS::DBInstance page of the CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html), there is no such property UpdateReplacePolicy
```
# cfn-lint rds.yml 
W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/RdsDBInstance from deletion
rds.yml:279:3
```

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.

```
  RdsDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      MasterUsername:
        Ref: DBMasterUsername
      MasterUserPassword:
        Fn::GetAtt:
        - RandomPassword
        - Random
      AllocatedStorage:
        Ref: AllocatedStorage
      StorageType:
        Ref: StorageType
      DBInstanceClass:
        Ref: DBInstanceType
      Engine:
        Ref: Engine
      EngineVersion:
        Ref: EngineVersion
      Iops:
        Fn::If:
        - StorageTypeIops
        - Ref: StorageIops
        - Ref: AWS::NoValue
      PubliclyAccessible: 'false'
      Port:
        Ref: DBInstancePort
      AutoMinorVersionUpgrade: 'true'
      AllowMajorVersionUpgrade:
        Ref: AllowMajorVersionUpgrade
      PreferredMaintenanceWindow: sun:20:00-sun:21:00
      BackupRetentionPeriod:
        Fn::If:
        - RdsBackupRetention
        - '35'
        - '14'
      MultiAZ:
        Fn::If:
        - RdsMultiAZ
        - 'true'
        - 'false'
      DBInstanceIdentifier:
        Ref: AppName
      DBName:
        Fn::If:
        - DBSnapshot
        - Ref: AWS::NoValue
        - Ref: DBName
      DBSubnetGroupName:
        Ref: DBSubnetGroupLocal
      DBParameterGroupName:
        Ref: DBParameterGroup
      EnableCloudwatchLogsExports: ['postgresql']
      DBSnapshotIdentifier:
        Fn::If:
        - DBSnapshot
        - Ref: DBSnapshotName
        - Ref: AWS::NoValue
      StorageEncrypted: 'true'
      CopyTagsToSnapshot: 'true'
      VPCSecurityGroups:
      - Ref: RDSSG
      Tags:
      - Key: Name
        Value:
          Ref: AppName
```
  * If present, please add links to the (official) documentation for clarification
[AWS::RDS::DBInstance page of the CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html)
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
