### ISSUE TITLE
ManagedPolicyArns throws error referring to policy created in the same template.

### ISSUE THREAD

**Issue by backpacked** [aws-cloudformation/cfn-lint#2234]
*cfn-lint version: cfn-lint 0.58.3

*Description of issue.*
Create IAM:
```
InstanceIamPolicy: 
    Type: 'AWS::IAM::ManagedPolicy'
    ...
```
Refer the policy in a new IAM:Role
```
Ec2InstanceRole:
    Type: "AWS::IAM::Role"
    ManagedPolicyArns:
        - !Ref: InstanceIamPolicy
        ...
```  
Linting shows an error
```
[cfn-lint] E3002: Property Resources/Ec2InstanceRole/Properties/ManagedPolicyArns/0 has an illegal function Fn::Ref:
```

**Comment by backpacked** [comment]
It should not be !Ref: but just Ref
```
Ec2InstanceRole:
    Type: "AWS::IAM::Role"
    ManagedPolicyArns:
        - *Ref*: InstanceIamPolicy
```
