### ISSUE TITLE
SubscriptionRoleArn is not a valid property of AWS::SNS::Subscription

### ISSUE THREAD

**Issue by cazzer** [aws-cloudformation/cfn-lint#2235]
*cfn-lint version: (`1.9.7`)*

_SubscriptionRoleArn is not a valid property of AWS::SNS::Subscription_ is thrown for the following subscription:
```
  SnsFirehoseSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: firehose
      Endpoint: !GetAtt EventStream.Arn
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SnsEvents
      SubscriptionRoleArn: !GetAtt EventSnsRole.Arn
      RawMessageDelivery: true
```

But this property is _required_ for `firehose` subscriptions, as per [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-subscriptionrolearn).
