### ISSUE TITLE
An error is shown when conditional `OptionConfigurations` attribute of `AWS::RDS::OptionGroup` resource is missing

### ISSUE THREAD

**Issue by Zyava** [aws-cloudformation/cfn-lint#2258]
*cfn-lint version: 0.59.0* 

`cfn-lint` produces an error when [conditional `OptionConfigurations` attribute of `AWS::RDS::OptionGroup` resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html) is missing

```
E3003 Property OptionConfigurations missing at Resources/DatabaseOptionGroup/Properties
```

*Description of issue.*

For some reason `OptionConfigurations` conditional attribute in the [`AWS::RDS::OptionGroup` spec] (https://d3teyb21fexa9r.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) is marked as required:

```json
    "AWS::RDS::OptionGroup": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html",
      "Properties": {
...
        "OptionConfigurations": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html#cfn-rds-optiongroup-optionconfigurations",
          "DuplicatesAllowed": true,
          "ItemType": "OptionConfiguration",
          "Required": true,
          "Type": "List",
          "UpdateType": "Immutable"
        },
```

and `cfn-lint` still produces an error

```
E3003 Property OptionConfigurations missing at Resources/DatabaseOptionGroup/Properties
```

However, both AWS Cloudformation service itself and `aws cloudformation validate-template` cli command accept template below without any errors.

```yaml
  DatabaseOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: mysql
      MajorEngineVersion: 8.0
      OptionGroupDescription: Database MySQL
      Tags:
      - Key: generated-by
        Value: cloudformation
```
