### ISSUE TITLE
AWS Application Insights Tier  and Log values aren't accepting any valid values

### ISSUE THREAD

**Issue by aelcinyc** [aws-cloudformation/cfn-lint#2271]
*cfn-lint version: (`cfn-lint --version`)*

*Description of issue.*
AWS::ApplicationInsights::Application.ComponentMonitoringSetting.Tier
AWS::ApplicationInsights::Application.Log.LogType
These 2 property types are not accepting any valid values defined within regex.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationinsights-application-log.html#cfn-applicationinsights-application-log-logtype

We see the regex details provided here
https://github.com/aws-cloudformation/cfn-lint/tree/main/src/cfnlint/data/CloudSpecs
which don''t reflect most recent source value defined here
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

Please provide as much information as possible:

Sample Template 
```
  myappinsights: 
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref CreateResourceGroup
      CWEMonitorEnabled: true
      OpsCenterEnabled: true
      OpsItemSNSTopicArn: !Ref SNSTopic
      AutoConfigurationEnabled: true
      ComponentMonitoringSettings:
      - ComponentName: !Ref SqlFSxFCIName
        Tier: 'SQL_SERVER'
        ComponentConfigurationMode: DEFAULT_WITH_OVERWRITE
        DefaultOverwriteComponentConfiguration:
          SubComponentTypeConfigurations:
            - SubComponentType: 'AWS::EC2::Instance'
              SubComponentConfigurationDetails:
                Logs:
                  - LogGroupName: !Sub 'SQL_SERVER-${ResourceGrpName}'
                    LogType: 'SQL_SERVER'
                    LogPath: >-
                      C:\Program Files\Microsoft SQL
                      Server\MSSQL**.MSSQLSERVER\MSSQL\Log\ERRORLOG
```
