### ISSUE TITLE
Incorrect coupling of AttributeDefinitions and KeySchema

### ISSUE THREAD

**Issue by nallenscott** [aws-cloudformation/cfn-lint#2295]
**Version**: 0.61.1 and latest spec files

**Resource**: AWS::DynamoDB::Table

**Problem**:
cfn-lint requires all attributes in `AttributeDefinitions` to exist in `KeySchema`.

**Argument**:
According the the official [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html), unless I'm reading it incorrectly, all of the attributes in `AttributeDefinitions` are not required to exist in `KeySchema`. It's vice versa, where all of the properties in `KeySchema` are required to exist in `AttributeDefinitions`, which I believe is also true of the attributes in `GlobalSecondaryIndexes.KeySchema` and `LocalSecondaryIndexes.KeySchema`. This is demonstrated in the official [examples](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#aws-resource-dynamodb-table--examples).

**Template**:

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: CampaignId
          AttributeType: S
        - AttributeName: Spend
          AttributeType: S
      KeySchema:
        - AttributeName: CampaignId
          KeyType: HASH
      TableName: rt-stats
```

**Screenshot**:

<img width="696" alt="Screen Shot 2022-06-28 at 3 14 12 PM" src="https://user-images.githubusercontent.com/11765848/176266294-e0454b70-a687-4efb-944f-b2632a8306e6.png">

**References**:
- https://github.com/aws-cloudformation/cfn-lint/pull/1284
