### ISSUE TITLE
AWS::EC2::KeyPair Ref error

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cfn-lint#2303]
*cfn-lint version: `0.61.2`

*Description of issue.*

With a KeyPair such as

```
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: MyKeyPair
      KeyType: ed25519
```

If you reference that KeyPair, such as `KeyName: !Ref KeyPair`, cfn-lint returns the follow error, even though this deploys as expected to CloudFormation:

`E3008: Property "KeyName" has no valid Refs to Resources at Resources/MyInstance/Properties/KeyName/Ref`
