### ISSUE TITLE
[E3002] CommaDelimitedList parameter value is not considered a list

### ISSUE THREAD

**Issue by Fulde** [aws-cloudformation/cfn-lint#2318]
*cfn-lint version: 0.61.4*

I am receiving the following error: 
```
E3002: Property Subnets should be of type List or Parameter should be a list for resource LoadTestRule
```

This occurs when using a CloudFormation SSM Parameter with the type `AWS::SSM::Parameter::Value<CommaDelimitedList>`, where the parameter value is assigned to a Property that expects a list of Strings. However, this error does not occur when the parameter's type is changed to `AWS::SSM::Parameter::Value<List<String>>`. According to the [CloudFormation Parameters documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types), these two types appear to be interchangeable.

This issue persists after updating both `cfn-lint` and the spec files.

This example produces the error on the `Subnets` property. Changing the parameter's type to `AWS::SSM::Parameter::Value<List<String>>` does not.
```yaml
LoadTestContainerSubnetParameter:
  Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
  Description: location of SSM parameter value, containing list of public subnets

# ...

LoadTestRule:
  Type: AWS::Events::Rule
  Properties:
    Description: Invoke nightly
    Name: !Sub '${ApplicationName}-load-test'
    ScheduleExpression: cron(0 3 ? * MON-FRI *)
    State: ENABLED
    Targets:
      - Arn: !GetAtt LoadTestEcsCluster.Arn
        RoleArn: !GetAtt LoadTestSchedulerRole.Arn
        Id: !Sub '${ApplicationName}-load-test'
        EcsParameters:
          EnableExecuteCommand: false
          LaunchType: FARGATE
          NetworkConfiguration:
            AwsVpcConfiguration:
              AssignPublicIp: ENABLED
              SecurityGroups:
                - !GetAtt ClusterSecurityGroup.GroupId
              Subnets: !Ref LoadTestContainerSubnetParameter
          TaskCount: 1
          TaskDefinitionArn: !Ref LoadTestTaskDefinition
```

**Comment by kddejong** [comment]
I'm having issues replicating this issue with the template you provided?  Are you able to replicate this error with that code?

**Comment by Fulde** [comment]
Here is a full template, with some placeholder values. It has the essentials to produce the error. I've double-checked that cfn-lint and the spec files are all updated.

```yaml
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LoadTestContainerSubnetParameter:
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Description: location of SSM parameter value, containing list of public subnets

Resources:
  LoadTestRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Invoke nightly
      Name: name
      ScheduleExpression: cron(0 3 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Arn: cluster_arn
          RoleArn: role_arn
          Id: id
          EcsParameters:
            EnableExecuteCommand: false
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups:
                  - sg-id123
                Subnets: !Ref LoadTestContainerSubnetParameter
            TaskCount: 1
            TaskDefinitionArn: task_def_arn
```
