### ISSUE TITLE
E3001 Invalid or unsupported Type Datadog::Monitors::Monitor for resource DatadogMonitorResource in us-east-1

### ISSUE THREAD

**Issue by elenacopaci** [aws-cloudformation/cfn-lint#2321]
cfn-lint version:  0.61.3 

I am receiving the following error:
`E3001 Invalid or unsupported Type Datadog::Monitors::Monitor for resource DatadogMonitorResource in us-east-1
`
I am integrating some Datadog custom resources in cloudformation:
```
Resources:
  DatadogMonitorResource:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
```

According to this [documentation](https://www.datadoghq.com/blog/monitoring-as-code-with-datadog-and-cloudformation/), it should be possible.
