### ISSUE TITLE
Fn::If in AWS::Serverless::Function-Events

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cfn-lint#2342]
*cfn-lint version:*  0.63.0

*Description of issue.*

I'm seeing a couple weird behaviors with `Fn:If` in the `Events` property of `AWS::Serverless::Function`.

When I do the following, I get a warning that `IsPrimaryRegion` is never used.

```yaml
Conditions:
  IsPrimaryRegion: !Equals [!Ref RegionMode, Primary]

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref CodeS3Bucket
        Key: !Ref CodeS3ObjectKey
      Events:
        ScheduleTrigger:
          Properties:
            Schedule: !Sub rate(${kScheduleIntervalMinutes} ${kScheduleIntervalLabel})
            Enabled: !If [IsPrimaryRegion, true, false]
          Type: Schedule
```

If I change to putting the entire event in an `If`:

```yaml
Conditions:
  IsPrimaryRegion: !Equals [!Ref RegionMode, Primary]

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref CodeS3Bucket
        Key: !Ref CodeS3ObjectKey
      Events:
        ScheduleTrigger: !If
          - IsPrimaryRegion
          - Properties:
              Schedule: !Sub rate(${kScheduleIntervalMinutes} ${kScheduleIntervalLabel})
              Enabled: true
            Type: Schedule
          - !Ref AWS::NoValue
```

It complains that `ScheduleTrigger` has no ID. (There are other `Events`, so that property is never empty).
