### ISSUE TITLE
Node16 support in Lambda Runtime

### ISSUE THREAD

**Issue by qmg-akara** [aws-cloudformation/cfn-lint#2352]
*cfn-lint version: (`cfn-lint --version`)*
0.59.0

*Description of issue.*
Hi guys, thanks for the great work!

We recently upgraded our Lambda functions to Node16 in a SAM template and started getting the following error:

```
[E3030: Check if properties have a valid value] (You must specify a valid value for Runtime (nodejs16.x). Valid values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7"]) matched ./template.yaml:123
```

CloudFormation template:
```yaml
...
Globals:
  Function:
    Runtime: nodejs16.x
...
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample-function
      CodeUri: dist
      ...
    Metadata:
      BuildMethod: makefile
```

Do you have any estimated time for supporting node16? Thanks
