### ISSUE TITLE
CloudWatch Logs Tags Property Not Failing for GovCloud

### ISSUE THREAD

**Issue by taylorbartley** [aws-cloudformation/cfn-lint#2396]
### CloudFormation Lint Version

0.66.0

### What operating system are you using?

Debian GNU/Linux 11 (bullseye)

### Describe the bug

CloudWatch Logs allow tag definitions via CloudFormation, but tags are not supported in GovCloud CFN (at least not US regions).

If my .cfnlintrc.yml only Gov regions, linting fails with "E3002 Invalid Property Resources/LogGroupFoo/Properties/Tags".

If my .cfnlintrc.yml contains a commercial region (or no regions), passes when tags are added to a Log Group.

### Expected behavior

Linting should fail when a Gov region is specified in .cfnlintrc.

### Reproduction template

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  LogGroupFoo:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}/foo
      RetentionInDays: 90
      Tags:
        - Key: Name
          Value: Sometag
    Metadata: # Suppressing KMS Error
      cfn_nag:
        rules_to_suppress:
          - id: W84
```
