### ISSUE TITLE
Add support for AWS::FSx::DataRepositoryAssociation

### ISSUE THREAD

**Issue by brianloyal** [aws-cloudformation/cfn-lint#2465]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

The CFN team added support for the new `AWS::FSx::DataRepositoryAssociation` resource in late October 2022. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-datarepositoryassociation.html

However, cfn-lint does not yet recognize it as a valid resource type. Can we please add it?

### Describe the solution you'd like

Add `AWS::FSx::DataRepositoryAssociation` as a valid CFN resource type

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
What version of cfn-lint are you using?

I haven't gone back to see what version of cfn-lint added support for this property but this template is valid for me.
```
Resources:
  Fsx:
    Type: AWS::FSx::DataRepositoryAssociation
    Properties:
      DataRepositoryPath: ""
      FileSystemPath: ""
      FileSystemId: "" 
```

You may need to update your version of `cfn-lint`
