### ISSUE TITLE
missing `AWS::CloudFront::MonitoringSubscription` resource type

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cfn-lint#2476]
### CloudFormation Lint Version

0.71.0

### What operating system are you using?

Ubuntu

### Describe the bug

Hello, i noticed resource type `AWS::CloudFront::MonitoringSubscription` is missing.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-monitoringsubscription.html
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html#enable-metrics

Looks like this resource has been added September 29, 2022.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

### Expected behavior

Resource type `AWS::CloudFront::MonitoringSubscription` should be accepted.

### Reproduction template

```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudFrontDistributionMonitoringSubscription:
    Type: AWS::CloudFront::MonitoringSubscription
    Properties:
      DistributionId: !Ref CloudFrontDistribution
      MonitoringSubscription:
        RealtimeMetricsSubscriptionConfig:
          RealtimeMetricsSubscriptionStatus: Enabled
```
