### ISSUE TITLE
E3002 Invalid Property Resources/xxx/Properties/FilterPolicyScope. Did you mean FilterPolicy?

### ISSUE THREAD

**Issue by lvthillo** [aws-cloudformation/cfn-lint#2500]
### CloudFormation Lint Version

cfn-lint 0.72.0

### What operating system are you using?

Mac (Intel)

### Describe the bug

`cfn-lint` complains about `FilterPolicyScope`:

```
E3002 Invalid Property Resources/AlertSubscription/Properties/FilterPolicyScope. Did you mean FilterPolicy?`
```

It seems it's also not yet here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html

But it's here: https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/

It also works when I try to deploy my subscription with a `FilterPolicyScope`

### Expected behavior

No complains

### Reproduction template

```yaml
  AlertSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: "xxx"
      Protocol: "email"
      FilterPolicyScope: MessageBody
      FilterPolicy: ...
```
