### ISSUE TITLE
False positive E3004 circular dependency for SAM templates

### ISSUE THREAD

**Issue by michael-k** [aws-cloudformation/cfn-lint#2501]
### CloudFormation Lint Version

cfn-lint 0.72.0

### What operating system are you using?

Linux

### Describe the bug

When `AWS::Serverless::Function` references an alarm in its `DeploymentPreference.Alarms` and the `AWS::CloudWatch::Alarm` references the function (eg. in Dimensions), a `E3004 Circular dependency` error is reported by cfn-lint.  Afaik this is a valid use case.

This was introduced in cfn-lint 0.72.0 (0.71.1 did not report E3004), most likely as part of PR aws-cloudformation/cfn-lint#2452.

```
E3004 Circular Dependencies for resource TestFunction. Circular dependency with [LatestVersionErrorMetricGreaterThanZeroAlarm]
template.yaml:5:3

E3004 Circular Dependencies for resource LatestVersionErrorMetricGreaterThanZeroAlarm. Circular dependency with [TestFunction]
template.yaml:28:3
```

(The template is based on https://gist.github.com/alexcasalboni/242071568a6adde805027345cfbb6d99.  But we first noticed this in one of our production functions when upgrading cfn-lint to 0.72.0.)

### Expected behavior

No E3004 is reported.

### Reproduction template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.test
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      CodeUri: ./
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /test
            Method: get
            RestApiId: !Ref 'Api'
      
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Alarms:
          - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: alarm-sam-demo-latestversion
      AlarmDescription: "alarm to check for errors in the function"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      Dimensions:
        - Name: FunctionName
          Value: !Ref TestFunction
        - Name: Resource
          Value: !Join [":", [!Ref TestFunction, !Select ["7", !Split [":", !Ref TestFunction.Version]]]]
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 1

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: foo
      TracingEnabled: true

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${FunctionName}
        - FunctionName: !Ref 'TestFunction'
      RetentionInDays: 1
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
```
