### ISSUE TITLE
DatabaseCluster.Endpoint.Address not recognized after --update-specs

### ISSUE THREAD

**Issue by FrederiqueRetsema** [aws-cloudformation/cfn-lint#2519]
### CloudFormation Lint Version

0.72.1, 0.72.2

### What operating system are you using?

Linux

### Describe the bug

When we use ``cfn-lint --update-specs``, the Endpoint.Address of the AWS::RDS::DBCluster isn't recognized anymore. This worked up to about 7 days ago.

Reproducing it is simple:
``docker run -it docker:20.10.12-alpine3.14``

In the Docker container:

```
apk add python3=~3.9
python3 -m ensurepip
pip3 install cfn-lint==0.72.2

<<Copy/paste below template into tst.yaml>>

cfn-lint --template tst.yaml
```

No output, works correctly

```
cfn-lint --update-specs
cfn-lint --template tst.yaml
   E1010 Invalid GetAtt DatabaseCluster.Endpoint.Address for resource MyCustomResource
   tst.yaml:33:9
```

According to the documentation, this should (still) work: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html

Replacing 0.72.2 by 0.72.1 doesn't solve the issue.

### Expected behavior

We would expect the template to pass without errors

### Reproduction template

```
Parameters:
  Pwd:
    Type: String
    NoEcho: true
    Default: "MyPa$$Word"

Resources:
  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 2
        AutoPause: false
      StorageEncrypted: true
      KmsKeyId: "whatever"
      DatabaseName: whatever
      MasterUsername: whatever
      MasterUserPassword: !Ref Pwd
      BackupRetentionPeriod: 30
      DBSubnetGroupName: "whatever"
      DBClusterParameterGroupName: default.aurora-mysql5.7
      VpcSecurityGroupIds:
        - "whatever"

  MyCustomResource:
    Type: Custom::MyCustomResource
    Properties:
      PasswordParameterName: '/databasecluster/password'
      Database:
        Host: !GetAtt DatabaseCluster.Endpoint.Address
        Port: 3306
        PasswordParameterName: '/database/password'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:MyCustomResource'
```
