### ISSUE TITLE
Linting with 0.73.0 doesn't accept property `TargetRole` of `AWS::RDS::DBProxyEndpoint`

### ISSUE THREAD

**Issue by matthiasgubler** [aws-cloudformation/cfn-lint#2579]
### CloudFormation Lint Version

0.73.0

### What operating system are you using?

Mac

### Describe the bug

When performing the `cfn-lint` I get the following error:
```
E3002 Invalid Property Resources/RDSProxyReadOnlyEndpoint/Properties/TargetRole
```

This property still appears on the doc here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxyendpoint.html

### Expected behavior

No linting issues

### Reproduction template

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  RDSProxyReadOnlyEndpoint:
    Type: AWS::RDS::DBProxyEndpoint
    Properties:
      DBProxyEndpointName: "rds-proxy-RO-endpoint"
      DBProxyName: 'name'
      VpcSubnetIds:
        - 123
      TargetRole: READ_ONLY

```
