### ISSUE TITLE
Custom rule greater and lesser operators are not numerical

### ISSUE THREAD

**Issue by kftsehk** [aws-cloudformation/cfn-lint#2612]
https://github.com/aws-cloudformation/cfn-lint/blob/55752dc40ee5935704c48ad7422dc98e1e71c88f/src/cfnlint/rules/custom/Operators.py#L132-L191

These lines are not comparing the Greater or Lesser operator numerically, and also not taken care of int input in yaml/json

Custom rule
```
AWS::Lambda::Function Timeout >= "5" ERROR "Have you forgot to set Timeout? 5s ain't doing anything."
```

# Case 1:

```yaml
Resources:
  TestNumericalPropertyLambda:
    Properties:
      PackageType: Zip
      Runtime: nodejs16.x
      Timeout: 100
    Type: AWS::Lambda::Function
```

fails for YAML numerical type due to error

```
E0002 Unknown exception while processing rule E9001: 'int' object has no attribute 'strip'
test.yml:1:1
```

# Case 2

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestNumericalPropertyLambda:
    Properties:
      PackageType: Zip
      Runtime: nodejs16.x
      Timeout: '100'
    Type: AWS::Lambda::Function
```

fails due to '100' < '5' of string comparison

```
E9001 Have you forgot to set Timeout? 5s ain't doing anything.
test.yml:5:7
```
