### ISSUE TITLE
Type String is not determined when port numbers in FromPort and ToPort are used with single (') or double (") quotes

### ISSUE THREAD

**Issue by tblinux** [aws-cloudformation/cfn-lint#2652]
### CloudFormation Lint Version

0.76.1

### What operating system are you using?

Mac

### Describe the bug

The type string is not determined when the port number is used with single (') or double ("") quotes in FromPort and ToPort in security group rules for AWS::EC2::SecurityGroup resource.

### Expected behavior

When single (') or double (") quotes are used in security group rules for AWS::EC2::SecurityGroup resource in the AWS CloudFormation template. 

**If string is used in FromPort, it should throw an error like below**

"E3012 Property Resources/DemoSecurityGroup/Properties/SecurityGroupIngress/0/FromPort should be of type Integer"

**If string is used in ToPort, it should throw an error like below**
"E3012 Property Resources/DemoSecurityGroup/Properties/SecurityGroupIngress/0/ToPort should be of type Integer"

### Reproduction template

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DemoSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: vpc-000000 #dummy vpc id
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
        - Description: Allowing port 22 for everyone
          IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: "0.0.0.0/0"
```
