### ISSUE TITLE
A VPC needs to have CIDR blocks specified

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#2690]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Vpc:
    Type: AWS::EC2::VPC
```

### Describe the solution you'd like

I want to catch the error `Either CIDR Block or IPv4 IPAM Pool and IPv4 Netmask Length must be provided`

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [x] ⚠️ This feature might incur a breaking change
