### ISSUE TITLE
RDS instance types

### ISSUE THREAD

**Issue by ashemedai** [aws-cloudformation/cfn-lint#270]
Apologies for another enhancement ticket, but just ran into this problem with a development team.

*Description of issue.*

The team was using:

```
  DatabaseDBClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Family: "aurora5.6"

  DBInstance1a:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: "db.m4.xlarge"
```

Which in CloudFormation will lead to the following eventual error:

> RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.m4.xlarge, Engine=aurora, EngineVersion=5.6.10a, LicenseModel=general-public-license. For supported combinations of instance class and database engine version, see the documentation.

Developer points to https://aws.amazon.com/rds/instance-types/ which has the db.m4.xlarge on it. It's only when you scroll to the absolute bottom that you see, in a smaller font mind you, the following:

> Not every instance type is supported for every database engine, version, edition or region. Please see the DB engine-specific pricing pages for details.

Which leads to https://aws.amazon.com/rds/aurora/pricing/ and that shows only r3/r4 is available for Aurora MySQL.

This seems like something that is easily lintable, provided there is some auxiliary files like the CloudFormation spec files. So is there something similar available for instance types available for these aspects?
