### ISSUE TITLE
(AWS::SSM::Document) `Invalid request provided: schemaVersion should be String` not recognized by cfn-lint

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cfn-lint#2728]
### CloudFormation Lint Version

cfn-lint 0.77.4

### What operating system are you using?

Windows 10

### Describe the bug

cfn-lint is unable to recognize that `schemaVersion: ` needs to be a string:

```yaml
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Command"
      Content:
        schemaVersion: 2.2
        mainSteps:
          - action: aws:runShellScript...
```

CloudFormation is throwing the following exception:

```
Resource handler returned message: "Invalid request provided: schemaVersion should be String
(Service: Ssm, Status Code: 400, Request ID: 6123eabf-1adf-4b9e-a2db-XXXXXXXX)"
(RequestToken: ac277c66-4ced-8306-88b3-XXXXXXXX, HandlerErrorCode: InvalidRequest)
```

### Expected behavior

cfn-lint should display this as an error.

### Reproduction template

```yaml
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Command"
      Content:
        schemaVersion: 2.2
        mainSteps:
          - action: aws:runShellScript...
```
