### ISSUE TITLE
Add support for Java 17 lambda runtime

### ISSUE THREAD

**Issue by dejwsz** [aws-cloudformation/cfn-lint#2734]
### CloudFormation Lint Version

cfn-lint 0.77.4

### What operating system are you using?

MacOS Ventura 13.3.1 (a)

### Describe the bug

Java 17 lambda runtime is already available but cfn-lint gives error about value `java17`.

### Expected behavior

Java17 runtime should be accepted.

### Reproduction template

```
Resources:
  TestAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: ....
      Runtime: java17
```
