### ISSUE TITLE
Invalid Property Resources/SESConfigurationSetDestination/Properties/EventDestination/SnsDestination

### ISSUE THREAD

**Issue by Slooz** [aws-cloudformation/cfn-lint#2764]
### CloudFormation Lint Version

0.77.8

### What operating system are you using?

Mac/Ubuntu

### Describe the bug

cfn-lint outputs:

Invalid Property Resources/SESConfigurationSetDestination/Properties/EventDestination/SnsDestination

But this is a valid property:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html#cfn-ses-configurationseteventdestination-eventdestination-snsdestination

### Expected behavior

cfn-lint doesn't output an error

### Reproduction template

```yaml
Resources:
  SESConfigurationSetDestination:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: Name
      EventDestination:
        Name: DestinationName
        Enabled: true
        MatchingEventTypes:
          - send
          - reject
          - bounce
          - complaint
          - delivery
        SnsDestination:
          TopicARN: Arn
```
