### ISSUE TITLE
E0002: Unknown exception while processing rule E1024: 'list' object has no attribute 'path'

### ISSUE THREAD

**Issue by lowkasen** [aws-cloudformation/cfn-lint#2778]
### CloudFormation Lint Version

cfn-lint 0.77.10

### What operating system are you using?

Mac

### Describe the bug

When validation checks run on a the Cidr function `!Cidr [ ipBlock, count, cidrBits ]`, the count and cidrBits doesn't validate more complex functions like the `!If` in the example.

### Expected behavior

Doesn't throw unknown exception

### Reproduction template

```yaml
PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !If
        - defineYourOwnSubnetCIDR
        - !Ref FirstTierSubnet1CIDR
        - !Select
          - 0
          - !Cidr
            - 10.0.0.0/24
            - !If [3AZ, 16, 8]
            - 4
```

**Comment by kddejong** [comment]
Found the issue and working to correct it.

**Comment by szotrj** [comment]
@kddejong can you confirm whether this should also support !If in the cidrBits index of !Cidr?
I'm getting an error for the following resource block
E0002 Unknown exception while processing rule E1024: 'list' object has no attribute 'path'

```yaml
NonRoutableSubnetA:
    DeletionPolicy: Delete
    DependsOn: NonRoutableCidrBlock
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select [0, !Cidr [!Ref NonRoutableCidr, !If [3AZs, 3, 2], !If [3AZs, 14, 15]]]
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VPCID"
      Tags:
        - Key: Name
          Value: !Sub "${VpcStackName}-NonRoutable-Subnet-A"
```
Thanks
