### ISSUE TITLE
E1019 error

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-cloudformation/cfn-lint#2810]
### CloudFormation Lint Version

v0.79.1

### What operating system are you using?

windows 11 22h2 python 3.10.11

### Describe the bug

[cfn-lint] E1029: Found an embedded parameter "${AWS::Region}" outside of an "Fn::Sub" at Resources/VPCDynamoDBEndpoint/Properties/ServiceName

[cfn-lint] E1029: Found an embedded parameter "${AWS::StackName}" outside of an "Fn::Sub" at Resources/PipelineS3EmptierRolePolicy/Properties/PolicyName

there was not an issue in v0.78.2. It only appears to be aws psedo parameters. I am also getting E3031 in the second snippet i added but i think that is a downstream effect of E1019 being thrown.

### Expected behavior

not to throw an error as the embedded parameter is inside a sub.

### Reproduction template

snippets of resources not working
```
  # DynamoDB VPC Endpoint Provisioning
  VPCDynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: ConditionCreateClientVpn
    Properties:
      RouteTableIds:
        - !Ref ClientVpnRouteTable1
        - !Ref ClientVpnRouteTable2
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcId:
        Fn::ImportValue: !Sub '${Region}-cvpn-vpc-id'
```

```
  PipelineS3EmptierRolePolicy:
    Type: AWS::IAM::Policy
    Condition: ConditionSandboxEnvironment
    Properties:
      PolicyName: !Sub '${AWS::StackName}-s3-emptier-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:ListBucket
              - s3:ListBucketVersions
            Resource:
              - !GetAtt ALBLogsBucket.Arn
              - !GetAtt CodeCopyBucket.Arn
              - !GetAtt S3AccessLogsBucket.Arn
          - Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource:
              - !Sub '${ALBLogsBucket.Arn}/*'
              - !Sub '${CodeCopyBucket.Arn}/*'
              - !Sub '${S3AccessLogsBucket.Arn}/*'
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource:
              - !Ref AWS::StackId
      Roles:
        - Fn::ImportValue: !Sub '${Region}-${VpcName}-${AppName}-pipeline-s3-emptier-role'
```

snippet without an error thrown (from the same template as the first example of one with an error:

```
  #Route 53 Records
  ClientVpnR53RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Condition: ConditionCreateClientVpnDns
    DependsOn:
      - ClientVpnRouteTableAz1Cidr1
      - ClientVpnRouteTableAz1Cidr2
      - ClientVpnRouteTableAz1Cidr3
      - ClientVpnRouteTableAz2Cidr1
      - ClientVpnRouteTableAz2Cidr2
      - ClientVpnRouteTableAz2Cidr3
    Properties:
      Comment: !Sub '${Region}-cvpn-${ClientVpnPurpose}-record-set'
      HostedZoneId: !FindInMap [ClientVpn, Acm, ZoneId]
      RecordSets:
        - Name: !FindInMap [ClientVpn, Acm, DomainName]
          Region: !FindInMap [RegionDetailsMap, !Ref Region, Name]
          SetIdentifier: !Sub 'cvpn-${ClientVpnPurpose}-${Region}'
          ResourceRecords:
            - !Sub 'vpn.${ClientVpnEndpoint}.prod.ClientVpn.${AWS::Region}.amazonaws.com'
          Type: CNAME
          TTL: '60'
```
