### ISSUE TITLE
E3001 error - AWS::ServiceCatalog::Portfolio

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-cloudformation/cfn-lint#2866]
### CloudFormation Lint Version

0.79.9

### What operating system are you using?

windows

### Describe the bug

AWS::ServiceCatalog::Portfolio is being reported as not supported in us-west-2 since 0.79.9. does report as supported in 0.79.8

deployed a test stack in us-west-2 and it deployed successfully.

### Expected behavior

resource type doesnt generate an error.

### Reproduction template

```
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Service Catalog Portfolio

Resources:
  # Service Catalog Portfolio
  SCPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      AcceptLanguage: en
      Description: 'Test - portfolio'
      DisplayName: 'Test - portfolio'
      ProviderName: Test

```
