### ISSUE TITLE
Using AWS::LanguageExtensions breaks VPCAccessPolicy usage

### ISSUE THREAD

**Issue by chris-redekop** [aws-cloudformation/cfn-lint#2896]
### CloudFormation Lint Version

0.79.10

### What operating system are you using?

Regolith

### Describe the bug

Adding the `AWS::LanguageExtensions` transformation before the SAM transformation causes cfn-lint to fail on a template that contains the `VPCAccessPolicy` policy template.  Removing the transformation allows cfn-lint to succeed as expected.

I tried updating the spec files but `cfn-lint -u` hangs.  (I waited ~> 30 min.)

```
$ cfn-lint mse.yaml
$ cfn-lint mfe.yaml
E0001 Error transforming template: Resource with id [MyFunction] is invalid. Policy at index 0 in the 'Policies' property is not valid
mfe.yaml:1:1

$ diff mse.yaml mfe.yaml 
2a3
>   - AWS::LanguageExtensions
```

### Expected behavior

I expect cfn-lint to succeed whether or not the `AWS::LanguageExtensions` transformation is specified.

### Reproduction template

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - VPCAccessPolicy: {}
```
