### ISSUE TITLE
E0002: Unknown exception while processing rule E2530: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-cloudformation/cfn-lint#2911]
### CloudFormation Lint Version

0.82.0

### What operating system are you using?

windows 11

### Describe the bug

receive the E2530 error even though i dont have SnapStart in my lambda resource

### Expected behavior

no error

### Reproduction template

if i remove this lambda resource, it doesnt throw the error
```
  Lambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaLogGroup
    Properties:
      Architectures:
        - !If
          - ConditionLambdaArmSupport
          - !Ref OSArchitechture
          - x86_64
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub '${Region}-${BusinessUnit}-${Environment}-${AppName}-artifact-s3-bucket'
        S3Key: !Ref LambdaS3Key
        S3ObjectVersion: !Ref LambdaS3ObjectVersion
      Description: !Sub 'Lambda Function - ${LambdaPurpose}'
      FunctionName: !Sub '${Region}-${BusinessUnit}-${Environment}-${AppName}-lambda-${LambdaPurpose}'
      Handler: !Ref LambdaHandler
      Layers:
        - !Ref LambdaLayer
      MemorySize: !Ref LambdaMemory
      Role: !GetAtt LambdaRole.Arn
      Runtime: !Ref LambdaRuntime
      Timeout: !Ref LambdaTimeout
      VpcConfig: !If
        - ConditionVpcAttachment
        - SecurityGroupIds:
            - Fn::ImportValue: !Sub '${Region}-${BusinessUnit}-${Environment}-${AppName}-sg-${LambdaPurpose}'
          SubnetIds:
            - Fn::ImportValue: !Sub '${Region}-${BusinessUnit}-${Environment}-${VpcAttachment}-subnet-1-id'
            - Fn::ImportValue: !Sub '${Region}-${BusinessUnit}-${Environment}-${VpcAttachment}-subnet-2-id'
            - !If
              - ConditionThirdAZ
              - Fn::ImportValue: !Sub '${Region}-${BusinessUnit}-${Environment}-${VpcAttachment}-subnet-3-id'
              - !Ref AWS::NoValue
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub '${Region}-${BusinessUnit}-${Environment}-${AppName}-lambda-${LambdaPurpose}'
        - Key: region-abbreviation
          Value: !Ref Region
        - Key: business-unit
          Value: !Ref BusinessUnit
        - Key: environment-type
          Value: !Ref Environment
        - Key: app-name
          Value: !Ref AppName
        - Key: service-type
          Value: !Ref Service
        - Key: cost-center
          Value: !Ref CostCenter
        - Key: compliance-type
          Value: !Ref Compliance
        - Key: owner-name
          Value: !Ref OwnerName
        - Key: owner-email-id
          Value: !Ref OwnerEmail
        - Key: patch-group
          Value: !Ref PatchGroup
        - Key: criticality-level
          Value: !Ref CriticalityLevel
        - Key: map-migrated
          Value: !Ref MapMigrated

```
