### ISSUE TITLE
Error shown when valid intrinsic functions used within DeletionPolicy & UpdateReplacePolicy

### ISSUE THREAD

**Issue by arthurboghossian** [aws-cloudformation/cfn-lint#2915]
### CloudFormation Lint Version

cfn-lint 0.80.2

### What operating system are you using?

Mac

### Describe the bug

Receive `[cfn-lint] E3035: DeletionPolicy only supports one of the Fn::FindInMap, Fn::If, Ref intrinsic functions for Resources/Topic/DeletionPolicy` when using valid intrinsic functions that are supported like `Fn::Join`, `Fn::Select`, `Fn::Sub`.

Also see no cfn-lint message when using invalid intrinsic functions nested within the DeletionPolicy & UpdateReplacePolicy attributes.

### Expected behavior

cfn-lint shouldn't give an error message when valid intrinsic functions like `Fn::Join`, and `Fn::Select`, and `Fn::Sub` are used.

Note: if the `Fn::GetAtt`, `Fn::GetAZs`, `Fn::ImportValue` intrinsic functions (or `Ref` to non-parameter and non-AWS pseudo-parameter) are included within the DeletionPolicy (including as a nested intrinsic function), the template is invalid and ideally this would be mentioned by cfn-lint.

### Reproduction template

```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Suffix:
    Type: String
    Default: 'elete'
Resources:
  Topic:
    DeletionPolicy: !Sub 'D${Suffix}'
    Type: AWS::SNS::Topic
```
