### ISSUE TITLE
Fn::Sub with Fn::GetAtt dot notation fails when AWS::LanguageExtensions Transform is included

### ISSUE THREAD

**Issue by arthurboghossian** [aws-cloudformation/cfn-lint#2972]
### CloudFormation Lint Version

cfn-lint 0.80.2

### What operating system are you using?

Mac

### Describe the bug

Receiving the following exception when including an Fn::Sub intrinsic function with Fn::GetAtt dot notation (Ex: `{"Fn::Sub": "${Role.Arn}"}`) when passed to the Role property of Lambda AND when the `AWS::LanguageExtensions` Transform is included within the template (where removing the `AWS::LanguageExtensions` Transform reference causes it to succeed):

```
E3031: Role contains invalid characters (Pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$) at Resources/Function/Properties/Role
```

### Expected behavior

Expect to no longer receive an error when the AWS::LanguageExtensions Transform is included with an Fn::Sub with Fn::GetAtt intrinsic function dot notation.

### Reproduction template

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: myrolename
      AssumeRolePolicyDocument: InsertRole
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: Bucket
        S3Key: Key
      Handler: index.handler
      Runtime: java8
      Role:
        "Fn::Sub": "${Role.Arn}"
```

where when the `AWS::LanguageExtensions` Transform is removed, the cfn-lint error is no longer shown.
