### ISSUE TITLE
AWS::CloudFormation::Stack TemplateBody property not recognized

### ISSUE THREAD

**Issue by sparr** [aws-cloudformation/cfn-lint#2975]
### CloudFormation Lint Version

0.83.4

### What operating system are you using?

MacOS 14.1

### Describe the bug

An `AWS::CloudFormation::Stack` resource with a TemplateBody property produces two errors. One E3003 for the missing required TemplateUrl property, one E3002 for the unrecognized TemplateBody property.

### Expected behavior

TemplateBody should be recognized as a valid alternative to TemplateUrl

### Reproduction template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody:
        AWSTemplateFormatVersion: '2010-09-09'
```
