### ISSUE TITLE
Output values are strict and must be a string

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#3013]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

When validating Output values they must be strict.  Meaning they have to be a string and boolean values won't work.

### Describe the solution you'd like

A rule that better validates the Output value.

### Additional context

Error: `Template format error: Every Value member must be a string. Rollback requested by user.`

Template
```
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Test
Outputs:
  Vpc:
    Value: !GetAtt Vpc.EnableDnsHostnames
```

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change
