### ISSUE TITLE
AWS::DynamoDB::Table - One key has to have Range when doing LSI

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#3110]
### Describe the feature you'd like to request

`One or more parameter values were invalid: Table KeySchema does not have a range key, which is required when specifying a LocalSecondaryIndex`

### Describe the solution you'd like

Detect this issue.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
```yaml
Table:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: Key
        KeyType: HASH
      AttributeDefinitions:
        - AttributeName: Key
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: test
          KeySchema:
          - AttributeName: Key
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
```
