### ISSUE TITLE
Condition Specified but with no condition passes linting but fails deploy

### ISSUE THREAD

**Issue by animaxcg** [aws-cloudformation/cfn-lint#3168]
### CloudFormation Lint Version

0.83.1

### What operating system are you using?

mac/ubuntu

### Describe the bug

in a cfn template if you specify root level item `Conditions` but have no conditions this passes cfn-lint but always fails on deploy

### Expected behavior

cfn-lint should fail if there is a Conditions root level object but no array entries under it.

### Reproduction template

```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  myParam
Conditions:
Resources:
  myTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: mytopic
      TopicName: mytopic
```
