### ISSUE TITLE
pre-commit updates to 1.2.5.a8 instead of 0.87.1

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-cloudformation/cfn-lint#3219]
### CloudFormation Lint Version

0.86.4

### What operating system are you using?

windows

### Describe the bug

updating the pre-commit configuration for cfn-lint via pre-commit autoupdate go to the v1.2.5a8 instead of the current version of v0.87.1

### Expected behavior

updates to (as of today) v0.87.1

### Reproduction template

n/a

**Comment by whoDoneItAgain** [comment]
same thing is happening even with the new v0.87.2 release. Only thing i can see different between 1.2.5a8 and the other alphas is it's tag doesnt have the precedding 'v'.

its version `1.2.5.a8` unlike the others `v1.2.5.a7` or `v0.87.2`

**Comment by kddejong** [comment]
Can you show me the cfn-lint pre-commit?  I can't replicate this issue with the following configuration.

```
repos:
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.87.1 # The version of cfn-lint to use
    hooks:
      - id: cfn-lint
        files: templates/.*\.(json|yml|yaml)$
```
