### ISSUE TITLE
v1: possible false-positive for `W3687`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cfn-lint#3317]
### CloudFormation Lint Version

cfn-lint 1.3.0

### What operating system are you using?

Windows 11

### Describe the bug

After updating from `v0.87.7` to `v1.3.0` i noticed a new finding, which is possibly a false-positive:

```yaml
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group"
      VpcId: !ImportValue VPC1-VPC-ID
      SecurityGroupIngress:
        - Description: "Test"
          IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
```

```sh
[cfn-lint] W3687: ['FromPort', 'ToPort'] are ignored when using 'IpProtocol' value 'TCP'
```

### Expected behavior

Not entirely sure what the issue here is, but `FromPort` and `ToPort` are not ignored:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-securitygroup-ingress.html

### Reproduction template

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group"
      VpcId: !ImportValue VPC1-VPC-ID
      SecurityGroupIngress:
        - Description: "Test"
          IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
```
