### ISSUE TITLE
v1: E1017 {'Fn::GetAtt': ['VPC', 'Ipv6CidrBlocks']} is not of type 'array'

### ISSUE THREAD

**Issue by egut** [aws-cloudformation/cfn-lint#3320]
### CloudFormation Lint Version

v1.3.0

### What operating system are you using?

Ubuntu

### Describe the bug

cfn-lint don't match to the right check it check for Ipv6CidrBlock**s** but the code say Ipv6CidrBlock (without s)

### Expected behavior

cfn-lint check with the right rule Ipv6CidrBlock

### Reproduction template

Example from AWS:
```yaml
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      Ipv6Native: true
      Ipv6CidrBlock: !Select [ 0, !Cidr [ !Select [ 0, !GetAtt myVpc.Ipv6CidrBlocks], 1, 64 ]]
      AssignIpv6AddressOnCreation: true
```
