### ISSUE TITLE
Incorrect E3006 Resource type 'AWS::SecretsManager::ResourcePolicy' does not exist in 'us-east-1'

### ISSUE THREAD

**Issue by sheridansmall** [aws-cloudformation/cfn-lint#3395]
### CloudFormation Lint Version

cfn-lint 1.3.4

### What operating system are you using?

Windows, Ubuntu 

### Describe the bug

When using AWS::SecretsManager::ResourcePolicy cfn-lint incorrectly reports "E3006 Resource type 'AWS::SecretsManager::ResourcePolicy' does not exist in 'us-east-1'".

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-resourcepolicy.html makes no mention of any AWS region.

AWS::SecretsManager::ResourcePolicy can exist in other regions.

### Expected behavior

I would not expect an error message when using AWS::SecretsManager::ResourcePolicy outside us-east-1 as AWS::SecretsManager::ResourcePolicy can exist in other regions.

### Reproduction template

```
---
AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline sample

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is a secret that I want to attach a resource-based policy to
  MySecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId:
        Ref: MySecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Resource: "*"
            Action: secretsmanager:DeleteSecret
            Effect: Deny
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
```
