### ISSUE TITLE
AWS::Lambda::EventSourceMapping defaulting to enforce StartingPosition when EventSourceArn is a reference/lookup

### ISSUE THREAD

**Issue by adamandrews** [aws-cloudformation/cfn-lint#3441]
### CloudFormation Lint Version

1.4.0, 1.4.2

### What operating system are you using?

Mac, Centos, RHEL

### Describe the bug

When using a parameter lookup as the `ARN` for `EventSourceArn` in the resource type `AWS::Lambda::EventSourceMapping`, cfn-lint is throwing error `E3633`.

### Expected behavior

This error should only show up when the `ARN` of `EventSourceArn` in the resource type `AWS::Lambda::EventSourceMapping` contains `(kinesis|kafka|dynamodb)`.

If this ARN pattern is not present, enforcement of `StartingPosition` should not be enforced during linting.

### Reproduction template

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
SES_EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: '{{resolve:ssm:/SQS_Queue/SQS_ARN}}'
      FunctionName: MyFunctionNameHere
```
