### ISSUE TITLE
E3002: Invalid Property Resources/Stackset/Properties/OperationPreferences/ConcurrencyMode

### ISSUE THREAD

**Issue by devvick** [aws-cloudformation/cfn-lint#3459]
### CloudFormation Lint Version

0.87.9

### What operating system are you using?

Archlinux - package from official repos

### Describe the bug

AWS::CloudFormation::StackSet OperationPreferences should allow ConcurrencyMode
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudformation-stackset-operationpreferences.html

### Expected behavior

`ConcurrencyMode` is a property launched in November 2023. cfn-lint should validate and allow this property.

### Reproduction template

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Stackset:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: myStackset
      PermissionModel: SERVICE_MANAGED
      CallAs: DELEGATED_ADMIN
      Capabilities:
        - CAPABILITY_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        FailureToleranceCount: 2
        MaxConcurrentCount: 3
        RegionConcurrencyType: PARALLEL
      TemplateURL: stackset.yml
```
