### ISSUE TITLE
E1019 error incorrectly reported for Fn::Sub function in AWS::CertificateManager::Certificate resource on cfn-lint v1.5.2

### ISSUE THREAD

**Issue by JHBoricua** [aws-cloudformation/cfn-lint#3485]
### CloudFormation Lint Version

1.5.2

### What operating system are you using?

Amazon Linux 2

### Describe the bug

I'm encountering an issue with cfn-lint, where it's reporting an E1019 error for the Fn::Sub function in an AWS::CertificateManager::Certificate resource, even though the function is receiving an array as expected.

Here's the relevant part of my CloudFormation template:

```
  Certificate:
    Condition: AccountIsCorrect
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateAuthorityArn: !Sub 'arn:${AWS::Partition}:acm-pca:us-east-1:myCaARN'
      DomainName: !Sub
        - '${CertificateCN}-${SdlcKey}.example.com'
        - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
      SubjectAlternativeNames: !If
        - IsProd
        - - !Sub
            - '${CertificateCN}-${SdlcEnvironment}.example.com'
            - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
              SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
          - !Sub
            - '${CertificateCN}.example.com'
            - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
        - !Sub
          - '${CertificateCN}-${SdlcEnvironment}.example.com'
          - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
            SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
```

The error message I'm seeing is:

```
[cfn-lint] E1019: {'Fn::Sub': ['${CertificateCN}-${SdlcEnvironment}.example.com', {'CertificateCN': {'Fn::FindInMap': ['Global', 'ALB', 'CertificateCN']}, 'SdlcEnvironment': {'Fn::FindInMap': ['SdlcKey', {'Ref': 'SdlcKey'}, 'SdlcEnvironment']}}]} is not of type 'array'
```

I believe this is a false positive, as the Fn::Sub function is indeed receiving an array. I'm using cfn-lint version 1.5.2. I cannot reproduce this when running against cfn-lint v0.87.9.

### Expected behavior

cfn-lint should correctly recognize the Fn::SUB function as receiving an array, and not report an E1019 error for this usage of the function. Instead, it should validate the template without any errors, assuming all other parts of the template are correct.

### Reproduction template

```
  Certificate:
    Condition: AccountIsCorrect
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateAuthorityArn: !Sub 'arn:${AWS::Partition}:acm-pca:us-east-1:myCaARN'
      DomainName: !Sub
        - '${CertificateCN}-${SdlcKey}.example.com'
        - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
      SubjectAlternativeNames: !If
        - IsProd
        - - !Sub
            - '${CertificateCN}-${SdlcEnvironment}.example.com'
            - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
              SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
          - !Sub
            - '${CertificateCN}.example.com'
            - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
        - !Sub
          - '${CertificateCN}-${SdlcEnvironment}.example.com'
          - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
            SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
```

**Comment by kddejong** [comment]
The problem is related to you not producing an array in the else path of the condition.

Change
```yaml
        - !Sub
          - '${CertificateCN}-${SdlcEnvironment}.example.com'
          - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
            SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
```
to 
```yaml
        - - !Sub
            - '${CertificateCN}-${SdlcEnvironment}.example.com'
            - CertificateCN: !FindInMap [ Global, ALB, CertificateCN ]
              SdlcEnvironment: !FindInMap [ SdlcKey, !Ref SdlcKey, SdlcEnvironment ]
```
