### ISSUE TITLE
E6101 Exception "Attribute for resource doesn't exist" raised while validating 'fn_getatt'  should not happen

### ISSUE THREAD

**Issue by dengmingtong** [aws-cloudformation/cfn-lint#3585]
### CloudFormation Lint Version

cfn-lint 1.9.7

### What operating system are you using?

Mac

### Describe the bug

Our template if fine for 1.9.0 but error E6101 happened for v1.9.7 version.

Below is the template snapshot:
 "Outputs": {
  "IngestionCommonResourcesIngestionServerDNS": {
   "Description": "Server DNS",
   "Value": {
    "Fn::If": [
     "IngestionCommonResourcesacceleratorEnableCondition0F76B8A4",
     {
      "Fn::GetAtt": [
       "IngestionCommonResourcesGlobalAcceleratorAB9F423D",
       "DnsName"
      ]
     },
     {
      "Fn::GetAtt": [
       "IngestionCommonResourcesCreateApplicationLoadBalancerALBclickstreamingestionservicealb6731C6BD",
       "DNSName"
      ]
     }
    ]
   }
  },

Error detail as below:
E6101 Exception "Attribute for resource doesn't exist" raised while validating 'fn_getatt'
cdk.out/Test.template.json:3926:6

the line 3926 is below part:

     _{
      "Fn::GetAtt": [
       "IngestionCommonResourcesGlobalAcceleratorAB9F423D",
       "DnsName"
      ]
     },_

Because we use the condition to control output value, the cfn-lint can support condition?

Thanks,
Mingtong

### Expected behavior

Should no error happened, I think the template should be fine.

### Reproduction template

```yaml
...
 "Outputs": {
  "IngestionCommonResourcesIngestionServerDNS": {
   "Description": "Server DNS",
   "Value": {
    "Fn::If": [
     "IngestionCommonResourcesacceleratorEnableCondition0F76B8A4",
     {
      "Fn::GetAtt": [
       "IngestionCommonResourcesGlobalAcceleratorAB9F423D",
       "DnsName"
      ]
     },
     {
      "Fn::GetAtt": [
       "IngestionCommonResourcesCreateApplicationLoadBalancerALBclickstreamingestionservicealb6731C6BD",
       "DNSName"
      ]
     }
    ]
   }
  },
...
```

**Comment by kddejong** [comment]
Yes it supports conditions for that validation but it won't really matter as long as the resource exists.  This is thrown from an attribute error that isn't caught.  Most of the time in the rules we aren't grabbing that attribute unless we know it exists but its possible we are missing. a try,except.

```yaml
Conditions:
  IngestionCommonResourcesacceleratorEnableCondition0F76B8A4: !Equals [!Ref "AWS::Region", "us-east-1"]
Resources:
  IngestionCommonResourcesGlobalAcceleratorAB9F423D:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: SampleAccelerator
      Enabled: true
  IngestionCommonResourcesCreateApplicationLoadBalancerALBclickstreamingestionservicealb6731C6BD:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: clickstream-ingestion-service-alb
      Scheme: internet-facing
      Type: application
      Subnets:
      - Fn::ImportValue: IngestionCommonStack-subnet-1-id
      - Fn::ImportValue: IngestionCommonStack-subnet-2-id
      - Fn::ImportValue: IngestionCommonStack-subnet-3-id
Outputs:
  IngestionCommonResourcesIngestionServerDNS:
   Description: Server DNS
   Value:
    Fn::If:
    - IngestionCommonResourcesacceleratorEnableCondition0F76B8A4
    - Fn::GetAtt: IngestionCommonResourcesGlobalAcceleratorAB9F423D.DnsName
    - Fn::GetAtt: IngestionCommonResourcesCreateApplicationLoadBalancerALBclickstreamingestionservicealb6731C6BD.DNSName
```

Do I have the right resource types?

also if you run cfn-lint with `--debug` we should be able to fine the stack trace.  I know where the ValueError is coming from but `fn_getatt` should be catching it and trying to figure out what line we are not catching it.
