### ISSUE TITLE
python 3.12 of ubi8 emits warning regarding tarfile

### ISSUE THREAD

**Issue by tbugfinder** [aws-cloudformation/cfn-lint#3586]
### CloudFormation Lint Version

1.9.5

### What operating system are you using?

ubi8 docker image

### Describe the bug

Installation of pre-commit hook raises following warning when executed in python 3.12 context.

```[INFO] This may take a few minutes...
/usr/lib64/python3.12/tarfile.py:2253: RuntimeWarning: The default behavior of tarfile extraction has been changed to disallow common exploits (including CVE-2007-4559). By default, absolute/parent paths are disallowed and some mode bits are cleared. See https://access.redhat.com/articles/7004769 for more details.
  warnings.warn(
```

### Expected behavior

ideally no warning message (?)

### Reproduction template

```
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v1.9.5
    hooks:
      - id: cfn-python-lint
        files: cfn-templates/.*\.(json|yml|yaml)$
```

-> pre-commit install

-> pre-commit run -a
