### ISSUE TITLE
Validate UpdatePolicy for AutoScalingRollingUpdate 

### ISSUE THREAD

**Issue by adamchainz** [aws-cloudformation/cfn-lint#362]
*cfn-lint version: (`cfn-lint --version`)* 0.7.2

*Description of issue.*

Using a template like:

```yaml
Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # ...
      MinSize: "1"
      MaxSize: "1"
      # ...
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
```

will fail at deployment time with an error from CloudFormation like:

> AWS::AutoScaling::AutoScalingGroup AutoScalingGroup UPDATE_FAILED: MinInstancesInService must be less than the autoscaling group's MaxSize

It would be nice to have protection against this. I guess there are other constraints, some are [in the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate). I submitted a [docs PR for this one](https://github.com/awsdocs/aws-cloudformation-user-guide/pull/164).
