### ISSUE TITLE
v1.11.1: E3002: Additional properties are not allowed ('RestartPolicy' was unexpected)

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cfn-lint#3642]
### CloudFormation Lint Version

1.11.1

### What operating system are you using?

Windows 11

### Describe the bug

`AWS::ECS::TaskDefinition` has a new parameter, but cfn-lint is unable to find it:

https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-restartpolicy.html

### Expected behavior

cfn-lint is able to find the parameter. Maybe the schemas need to be updated?

### Reproduction template

```yaml
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt ECSTaskIAMRole.Arn
      ExecutionRoleArn: !GetAtt ECSExecutionIAMRole.Arn
      NetworkMode: awsvpc
      RuntimePlatform:
        CpuArchitecture: ARM64
      Cpu: 1024
      Memory: 2048
      ContainerDefinitions:
        - Name: "Container"
          Image: <image>
          ReadonlyRootFilesystem: true
          RestartPolicy: # <---
            Enabled: true
          PortMappings:
            - ContainerPort: 443 # TCP
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref ECSLogGroup
              awslogs-stream-prefix: !Ref AWS::StackName
```
