### ISSUE TITLE
Support for SourceSecurityGroupId under SecurityGroupEgress in AWS::EC2::SecurityGroup

### ISSUE THREAD

**Issue by Hamitamaru** [aws-cloudformation/cfn-lint#371]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.7.3

*Description of issue.*
For some reason I get:
```
E3002 Invalid Property Resources/LaServiceEndpointSecurityGroup/Properties/SecurityGroupEgress/0/SourceSecurityGroupId
template.yml:1483:9
```
for
```
  LaServiceEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: LaServiceEndpointSecurityGroup
      GroupDescription: Security Group for VPC endpoints in the Lambda subnets
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId:
          Fn::GetAtt: [LambdaCanCallLaServiceSecurityGroup, GroupId]
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId:
          Fn::GetAtt: [LambdaCanCallLaServiceSecurityGroup, GroupId]
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: LaServiceEndpointSecurityGroup
        - Key: Stage
          Value: {Ref: Stage}
```
The odd part is it doesn't complain about SourceSecurityGroupId under SecurityGroupIngress only SecurityGroupEgress
