### ISSUE TITLE
Both CidrBlock and Ipv4NetmaskLength cannot be specified

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#3729]
### Describe the feature you'd like to request

When doing 

```
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.0.0/24
      Ipv4NetmaskLength: 10
```

### Describe the solution you'd like

Detect the error `Both CidrBlock and Ipv4NetmaskLength cannot be specified`

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change
