### ISSUE TITLE
AWS::EC2::NetworkInterface - additional interface types

### ISSUE THREAD

**Issue by david-w-webb** [aws-cloudformation/cfn-lint#3791]
### CloudFormation Lint Version

cfn-lint-1.18.1

### What operating system are you using?

Windows

### Describe the bug

I'm getting an error "[cfn-lint] E3030: 'nat_gateway' is not one of ['branch', 'efa', 'trunk']" when I attempt to set an AWS::EC2::NetworkInterface InterfaceType: parameter to 'nat_gateway'.

AWS Documentation indicates that valid values include: `api_gateway_managed | aws_codestar_connections_managed | branch | ec2_instance_connect_endpoint | efa | efa-only | efs | gateway_load_balancer | gateway_load_balancer_endpoint | global_accelerator_managed | interface | iot_rules_managed | lambda | load_balancer | nat_gateway | network_load_balancer | quicksight | transit_gateway | trunk | vpc_endpoint`

[API_NetworkInterface](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_NetworkInterface.html)

Note: CloudFormation documentation does not match API documentation.

[CloudFormation aws-resource-ec2-networkinterface](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-networkinterface.html)

### Expected behavior

Any of the allowed values should be permitted.

### Reproduction template

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Create initial VPC for Environment
Parameters:
  Division:
    Type: String
    Description: Name of the department.
    Default: cce
  EnvironmentType:
    Type: String
    Description: Environment name
    Default: lab
  RegionCode:
    Type: String
    Default: uea1
  ProjectName:
    Type: String
    Description: Name of the project
    Default: eks
  Iteration:
    Type: String
    Description: Specify the Iteration for resource
    Default: '001'
Resources:
  NetworkInterface1atgw:
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      Description: !Sub Interface for NAT Gateway ngw-${Division}-${EnvironmentType}-${RegionCode}-${ProjectName}-az1a-tgw-${Iteration}
      # PrivateIpAddress: "10.1.19.40"
      PrivateIpAddresses:
        - PrivateIpAddress: "10.1.19.40"
          Primary: true
      SecondaryPrivateIpAddressCount: 0
      # Ipv6PrefixCount: 0
      # Ipv4Prefixes: []
      # Ipv4PrefixCount: 0
      # GroupSet: []
      # Ipv6Prefixes: []
      SubnetId: !Ref PrivateSubnet1atgw
      SourceDestCheck: false
      InterfaceType: nat_gateway #branch  # "null"
      Tags:
        - Key: Name
          Value: !Sub 'eni-${Division}-${EnvironmentType}-${RegionCode}-${ProjectName}-az1a-tgw-${Iteration}'
        - Key: jbl:name
          Value: !Sub 'eni-${Division}-${EnvironmentType}-${RegionCode}-${ProjectName}-az1a-tgw-${Iteration}'
```
