### ISSUE TITLE
cfn-lint -iW causes template metadata to be ignored

### ISSUE THREAD

**Issue by ispyinternet** [aws-cloudformation/cfn-lint#3839]
### CloudFormation Lint Version

cfn-lint 1.20.0

### What operating system are you using?

Amazon Linux 2

### Describe the bug

I have the following metadata:

```
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3006
  ```

### Expected behavior

if I run cfn-lint template.yaml I only see the warnings
if I run cfn-lint -iW template.yaml I still get the E3006 error

### Reproduction template

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3006
        
Resources:
  GoogleClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Properties:
      Name: "/ClientSecret"
```
