### ISSUE TITLE
cfn-lint considers configuration broken when ignore_templates doesn't match any files

### ISSUE THREAD

**Issue by dmarinuswoodwing** [aws-cloudformation/cfn-lint#3881]
### CloudFormation Lint Version

1.22.0

### What operating system are you using?

Linux

### Describe the bug

cfn-lint considers configuration broken when ignore_templates doesn't match any files

We've added `node_modules/**` to `ignore_templates` but now cfn-lint fails since 1.22.0 when this directory doesn't exists / is empty.

The error message is non descriptive:

```
E0003 node_modules/** could not be processed by glob.glob
None:1:1
```

https://github.com/aws-cloudformation/cfn-lint/blob/f920591a75883f7b0b431bb414cdd627d9b1c627/src/cfnlint/config.py#L799-L800

Seems to be introduced by #3862 / @kddejong 

### Expected behavior

Allow excluding of templates that don't exists.

### Reproduction template

Use the following `.cfnlintrc`

```yaml
regions:
  - us-east-1
  - eu-west-1
templates:
  - "**/*.yaml"
  - "**/*.yml"
ignore_templates:
  - "node_modules/**"
```

**Comment by kddejong** [comment]
The quick solution is `ignore_bad_template` but going to leave this open as I am researching a few more things.

```yaml
regions:
  - us-east-1
  - eu-west-1
templates:
  - "**/*.yaml"
  - "**/*.yml"
ignore_bad_template: true
ignore_templates:
  - "node_modules/**"
```
