### ISSUE TITLE
AWS::EC2::VPCEndpoint Tags not allowed

### ISSUE THREAD

**Issue by ctp-consulting** [aws-cloudformation/cfn-lint#3894]
### CloudFormation Lint Version

1.22.2

### What operating system are you using?

Windows

### Describe the bug

The following error appears when Tags are specified for a VPC Endpoint resource.
[cfn-lint] E3002: Additional properties are not allowed ('Tags' was unexpected)

cfn-lint is used from VS Code's CloudFormation Linter extension

### Expected behavior

As shown below, it is configurable in the Cloudformation configuration and should not cause errors in cfn-lint.
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

### Reproduction template

sample code
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This is the Hoge VPC network backend stack.

Resources:
  HogeEC2VPCEndpointS3:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Gateway"
      VpcId: !Ref HogePublicVPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - !Ref HogePublicRouteTable
        - !Ref HogePrivateSubnetRouteTable
      PrivateDnsEnabled: false
      Tags:
        - Key: SystemName
          Value: Hoge
```
