### ISSUE TITLE
W8003 False positive when parameters have default values

### ISSUE THREAD

**Issue by CarlyG55** [aws-cloudformation/cfn-lint#3899]
### CloudFormation Lint Version

1.22.3

### What operating system are you using?

Ubuntu

### Describe the bug

The linter errors with W8003 on the following example, since it thinks the value of the parameter is always the default value, when there are multiple possible options that would lead to true or false

### Expected behavior

W8003 is not raised

### Reproduction template

```yaml
Parameters:
  Environment:
    Description: "The name of the environment to deploy to."
    Type: "String"
    Default: local
    AllowedValues:
      - "local"
      - "staging"
      - "integration"
      - "production"
    DeploymentName:
    Type: String
    MaxLength: 22
    AllowedPattern: ^.*[^-]$
    Default: test
    Description: A unique prefix to identify the deployment; used to distinguish variation between ephemeral stacks

Rules:
  DeploymentNameRequired:
    RuleCondition: !Equals [ !Ref Environment, "local" ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref DeploymentName, "" ] ]
        AssertDescription: >
          Must specify DeploymentName parameter when Environment is "local"
```
