### ISSUE TITLE
E2015 fails on invalid default value

### ISSUE THREAD

**Issue by DanielMcDonaldPOR** [aws-cloudformation/cfn-lint#3930]
### CloudFormation Lint Version

1.22.7

### What operating system are you using?

Ubuntu

### Describe the bug

This template causes E2015 to crash:

```
E0002 Unknown exception while processing rule E2015: "'bool' object has no attribute 'split'"
```

### Expected behavior

Anything but an unknown exception

### Reproduction template

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ParamName:
    Type: List<String>
    Description: Gobledygook
    Default: False
```
