### ISSUE TITLE
ECS Task definition container log driver enum does not include "sumologic"

### ISSUE THREAD

**Issue by fidelperez** [aws-cloudformation/cfn-lint#3933]
Our team uses the somologic log driver in container definitions. It appears that when validation was added sub properties, "sumologic" was not included in the enum used to validate LogDriver types. This change seems to have been introduced in issue #3763. 

Here's an example of where we are using the sumologic log driver. 

```yaml
TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: nginx
          Essential: true
          Image: !Sub  <accountId>.dkr.ecr.${AWS::Region}.amazonaws.com/<imageName>:latest
          Memory: 16
          PortMappings:
            - ContainerPort: 443
          Links:
            - app
          LogConfiguration:
            LogDriver: sumologic
            Options:
              sumo-url: !GetAtt SumoUrl.Value
              sumo-source-category: !Sub ${Environment}/${ProjectName}/access
```

When we execute cfn-lint the following error is returned.

```
E3030 'sumologic' is not one of ['awsfirelens', 'awslogs', 'fluentd', 'gelf', 'journald', 'json-file', 'splunk', 'syslog']
ci/service.template:234:13
```

Is resolving this just a matter of extending the enum to include "sumologic" log driver? If so, I can contribute this and submit a PR.
