### ISSUE TITLE
[cfn-lint] E8003: {'Fn::ImportValue': 'Stage'} is not of type 'string' when inside Fn::FindInMap

### ISSUE THREAD

**Issue by msplival** [aws-cloudformation/cfn-lint#3949]
### CloudFormation Lint Version

1.24.0

### What operating system are you using?

Ubuntu 24.04

### Describe the bug

I have a CloudFormation code snippet that looks like this:

```
Conditions:
  DeployEC2:
    Fn::Equals:
      - Fn::FindInMap:
        - PropertiesMap
        - DeployControllEC2
        - !Ref Stage
      - "true"
```

That cfn-lint has no problems with. 

But, for this I have to define a parametar called Stage. I'd like to import that value from the export of another stack, so I changed the snippet like this:

```
Conditions:
  DeployEC2:
    Fn::Equals:
      - Fn::FindInMap:
        - PropertiesMap
        - DeployControllEC2
        - !ImportValue Stage
      - "true"
```

Now I'm getting the error:

`[cfn-lint] E8003: {'Fn::ImportValue': 'Stage'} is not of type 'string'`

Why is this happening? My export, indeed, is a type of string - and !ImportValue indeed does return a string. 

Is this a problem with the way !ImportValue is used within FindInMap? 

### Expected behavior

I'd expect cfn-lint not to complain here, because !ImportValue indeed does return a string.

### Reproduction template

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Stage:
    Type: String
    Default: dev

Mappings:
  PropertiesMap:
    DeployControllEC2:
      dev: true
      prod: true

Conditions:
  DeployEC2:
    Fn::Equals:
      - Fn::FindInMap:
        - PropertiesMap
        - DeployControllEC2
        - !ImportValue Stage
      - "true"
```
