### ISSUE TITLE
Feature Request: `AWS::IAM::Role` - recognize if 2 `Sid`s in an InlinePolicy are the same

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cfn-lint#3973]
### Describe the feature you'd like to request

Currently cfn-lint doesn't recognize in an AWS::IAM::Role Inline Policy if 2 SIDs are the same. Example:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  ScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: "KMSAccess" # <----------
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  - kms:Encrypt
                Resource: "*"
              - Sid: "KMSAccess" # <----------
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  - kms:Encrypt
                Resource: "*"
```

This will result in the following CloudFormation exception:

```
Resource handler returned message:
"Statement IDs (SID) in a single policy must be unique.
(Service: Iam, Status Code: 400, Request ID: c0...)"
(RequestToken: b7..., HandlerErrorCode: InvalidRequest)
```

### Describe the solution you'd like

It would be great if cfn-lint would generate an error for this.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change
