### ISSUE TITLE
E3012 for Fn::Rain::S3Http

### ISSUE THREAD

**Issue by chdanielmueller** [aws-cloudformation/cfn-lint#4006]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

I would like to use [AWS Rain](https://github.com/aws-cloudformation/rain) extensions like `!Rain::S3Http` without it returning the error `E3012 {'Fn::Rain::S3Http': 'substack.yml'} is not of type 'string'`.
I tried to write a custom schema without success.

### Describe the solution you'd like

Sample Schema which solves this issue
or
Possibility to enable Rain Extensions via cfn-lint config.
e.g. `.cfnlintrc`
```yaml
rain: true
```

### Additional context

Sample Template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a substck via AWS Rain

Resources:

  SubStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Rain::S3Http substack.yml
      Parameters:
        Parameter1: Test
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change
