### ISSUE TITLE
Using the Dockerfile will always provide the latest version no matter the git branch specified in the build context

### ISSUE THREAD

**Issue by gautaz** [aws-cloudformation/cfn-lint#4010]
### CloudFormation Lint Version

N/A

### What operating system are you using?

Nixos

### Describe the bug

Building a Docker image with the following compose.yaml:
```yaml
services:
  cfn-lint:
    build:
      context: https://github.com/aws-cloudformation/cfn-lint.git#v1.27.0
```

will result with the latest cfn-lint available on pypi.org and not the one specified in the context.

### Expected behavior

I expect the build to provide the cfn-lint version that the branch of the repository would provide.

### Reproduction template

N/A
