### ISSUE TITLE
W3037: Errors with permission not in template

### ISSUE THREAD

**Issue by alex9smith** [aws-cloudformation/cfn-lint#4035]
### CloudFormation Lint Version

cfn-lint 1.31.2

### What operating system are you using?

Mac, Ubuntu

### Describe the bug

cfn-lint is failing both locally and in our CI with the error 
```bash
 $ cfn-lint -t template.yaml
W3037 'changemessagevisibilitybatch' is not one of ['addpermission', 'cancelmessagemovetask', 'changemessagevisibility', 'createqueue', 'deletemessage', 'deletequeue', 'getqueueattributes', 'getqueueurl', 'listdeadlettersourcequeues', 'listmessagemovetasks', 'listqueues', 'listqueuetags', 'purgequeue', 'receivemessage', 'removepermission', 'sendmessage', 'setqueueattributes', 'startmessagemovetask', 'tagqueue', 'untagqueue']
template.yaml:387:1

W3037 'deletemessagebatch' is not one of ['addpermission', 'cancelmessagemovetask', 'changemessagevisibility', 'createqueue', 'deletemessage', 'deletequeue', 'getqueueattributes', 'getqueueurl', 'listdeadlettersourcequeues', 'listmessagemovetasks', 'listqueues', 'listqueuetags', 'purgequeue', 'receivemessage', 'removepermission', 'sendmessage', 'setqueueattributes', 'startmessagemovetask', 'tagqueue', 'untagqueue']
template.yaml:387:1

```

These are SQS permissions, but our template does not set the `sqs:ChangeMessageVisibilityBatch` or `sqs:DeleteMessageBatch` permissions. It does however set `sqs:ChangeMessageVisibility` and `sqs:DeleteMessage` - I believe this is where the error is originating from.

I have tried to replicate the error with a minimum example however the below template passes: 
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "demo"
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Mappings:
  ExternalAccounts:
    production:
      AccountNumber: "000000000000"

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                !FindInMap [ExternalAccounts, !Ref Environment, AccountNumber]
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource: !GetAtt Queue.Arn
```

### Expected behavior

cfn-lint should not raise an error or warning for use of a permission that's not used in a template.

It would also be very helpful for debugging if the reported line for the warning could be the line in the template where the error happens, not the start of the `Resources` block.

### Reproduction template

https://github.com/govuk-one-login/di-account-management-backend/blob/main/template.yaml#L608-L623
