### ISSUE TITLE
E3510 error raised with version >=v1.31.0

### ISSUE THREAD

**Issue by anthony-nhs** [aws-cloudformation/cfn-lint#4037]
### CloudFormation Lint Version

1.31

### What operating system are you using?

linux

### Describe the bug

With this template
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DashboardViewerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DashboardViewer
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - apigateway:GET
            Resource:
             - "arn:aws:apigateway:eu-west-2::/restapis/*"
```
It passes using cfn-lint v1.30.0

With v1.31.0 it throws error
```
E3510 Exception "'AccessLogSettings'" raised while validating 'cfnLint'
```

### Expected behavior

cfn-lint passes

### Reproduction template

```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DashboardViewerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DashboardViewer
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - apigateway:GET
            Resource:
             - "arn:aws:apigateway:eu-west-2::/restapis/*"
```
