### ISSUE TITLE
Step Functions JSONata isn't fully supported (E3601)

### ISSUE THREAD

**Issue by gliptak** [aws-cloudformation/cfn-lint#4050]
### CloudFormation Lint Version

1.32.0

### What operating system are you using?

Mac

### Describe the bug

The CF template was constructed from YAML export from Step Functions editor. Below E3601 errors shown:

```
E3601 Only one of ['And', 'BooleanEquals', 'BooleanEqualsPath', 'IsBoolean', 'IsNull', 'IsNumeric', 'IsPresent', 'IsString', 'IsTimestamp', 'Not', 'NumericEquals', 'NumericEqualsPath', 'NumericGreaterThan', 'NumericGreaterThanPath', 'NumericGreaterThanEquals', 'NumericGreaterThanEqualsPath', 'NumericLessThan', 'NumericLessThanPath', 'NumericLessThanEquals', 'NumericLessThanEqualsPath', 'Or', 'StringEquals', 'StringEqualsPath', 'StringGreaterThan', 'StringGreaterThanPath', 'StringGreaterThanEquals', 'StringGreaterThanEqualsPath', 'StringLessThan', 'StringLessThanPath', 'StringLessThanEquals', 'StringLessThanEqualsPath', 'StringMatches', 'TimestampEquals', 'TimestampEqualsPath', 'TimestampGreaterThan', 'TimestampGreaterThanPath', 'TimestampGreaterThanEquals', 'TimestampGreaterThanEqualsPath', 'TimestampLessThan', 'TimestampLessThanPath', 'TimestampLessThanEquals', 'TimestampLessThanEqualsPath'] is a required property
test1.yml:14:17

E3601 Additional properties are not allowed ('Output' was unexpected)
test1.yml:21:13

E3601 Additional properties are not allowed ('Arguments' was unexpected)
test1.yml:27:13
```

### Expected behavior

No lint errors

### Reproduction template

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: arn:aws:iam::123456789123:role/myRole
      Definition:
        Comment: Reading messages from an SQS queue and iteratively processing each message.
        QueryLanguage: JSONata
        StartAt: Read messages from SQS queue
        States:
          Are there messages to process?:
            Choices:
              - Condition: '{% $exists($states.input.Messages) %}'
                Next: Pass
            Default: Finish
            Type: Choice
          Pass:
            Type: Pass
            Next: Finish
            Output: '{% $states.input %}'
            Assign:
              timestamp: '{% $now() %}'
          Finish:
            Type: Succeed
          Read messages from SQS queue:
            Arguments:
              AttributeNames:
                - All
              MaxNumberOfMessages: 10
              QueueUrl: https://sqs.us-east-1.amazonaws.com/123456789123/myQueue
              VisibilityTimeout: 30
              WaitTimeSeconds: 20
            Next: Are there messages to process?
            Resource: arn:aws:states:::aws-sdk:sqs:receiveMessage
            Type: Task
```
