### ISSUE TITLE
TypeError when validating templates with nested applications

### ISSUE THREAD

**Issue by mbfreder** [aws-cloudformation/cfn-lint#4056]
### CloudFormation Lint Version

1.32.0

### What operating system are you using?

Mac

### Describe the bug

When using cfn-lint (v1.32.0) to validate templates that contain AWS::Serverless::Application resources with local template references, the linter crashes with the following error:

`Error: expected str, bytes or os.PathLike object, not NoneType`

This is affecting SAM CLI. Please see this [issue](https://github.com/aws/aws-sam-cli/issues/7956)

It looks like the issue was introduced in cfn-lint v1.30.0 with commit e3b60eccd7d178ef7fe113abdfe5f85b9f74b5f5 ("Support GetAtts for nested stacks and outputs"). The public API function `lint()` in `cfnlint/api.py` explicitly passes `None` as the filename parameter when called via `runner.validate_template(None, template)`, but `_nested_stack_get_atts` function doesn't check if the filename parameter is None before using it with `os.path.abspath()`.

### Expected behavior

In version <= 1.25.1, `cfn-lint template.yml` returns no error.

### Reproduction template

```
cat << 'EOF' > template.yml
AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  MyServerlessApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: template.serverless.yml
EOF

cat << 'EOF' > template.serverless.yml
AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api

EOF
```
