### ISSUE TITLE
AWS::ApiGatewayV2::Api 'IpAddressType' not supported

### ISSUE THREAD

**Issue by nosnilmot** [aws-cloudformation/cfn-lint#4058]
### CloudFormation Lint Version

cfn-lint 1.32.1 / git eecec889d

### What operating system are you using?

Mac

### Describe the bug

`cfn-lint` does not recognize the (new) `IpAddressType` property for `AWS::ApiGatewayV2::Api` resources

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#cfn-apigatewayv2-api-ipaddresstype

```
$ cfn-lint apigateway.yaml
E3002 Additional properties are not allowed ('IpAddressType' was unexpected)
apigateway.yaml:8:7
```

### Expected behavior

cfn-lint passes

### Reproduction template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: HTTP
      IpAddressType: dualstack
```
