### ISSUE TITLE
E3682 for StorageEncrypted on AWS::RDS::DBInstance

### ISSUE THREAD

**Issue by pbrisbin** [aws-cloudformation/cfn-lint#4068]
### CloudFormation Lint Version

1.32.3

### What operating system are you using?

Arch Linux, Ubuntu

### Describe the bug

```yaml
  AuroraPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      EngineVersion: "16.2"
      StorageEncrypted: !Ref "StorageEncrypted"
      DBClusterIdentifier: !Ref "AuroraCluster"
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: false
      DBSubnetGroupName: !ImportValue "networking-RdsSubnetGroup"
      MonitoringRoleArn: !GetAtt "EnhancedMonitoringRole.Arn"
      MonitoringInterval: 15
      Engine: aurora-postgresql
      DBInstanceClass: !Ref "PrimaryInstanceClass"
      DBInstanceIdentifier: !Ref "PrimaryInstanceIdentifier"
      EnablePerformanceInsights: true
      DBParameterGroupName: !Ref "AWS::NoValue"
      Tags:
        - Key: role
          Value: rds-primary
```

```
E3682 Additional properties are not allowed (['StorageEncrypted'])
templates/progress-aurora-cluster.yaml:134:5
```

Removing the "additional" property indeed triggers change,

```
Changes for stacks/xxxx.freckle/us-east-1/progress/prod/aurora-cluster.yaml:
  Modify AuroraPrimaryInstance (AWS::RDS::DBInstance) progress-db-aurora-primary-prod
    Replacement: True
    Scope: Properties
    Details:
      * DirectModification in Properties (StorageEncrypted), recreation Always
```

### Expected behavior

cfn-lint should not report this property as additional/unnecessary, since CloudFormation appears to want to use it.

### Reproduction template

```yaml
  AuroraPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      EngineVersion: "16.2"
      StorageEncrypted: !Ref "StorageEncrypted"
      DBClusterIdentifier: !Ref "AuroraCluster"
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: false
      DBSubnetGroupName: !ImportValue "networking-RdsSubnetGroup"
      MonitoringRoleArn: !GetAtt "EnhancedMonitoringRole.Arn"
      MonitoringInterval: 15
      Engine: aurora-postgresql
      DBInstanceClass: !Ref "PrimaryInstanceClass"
      DBInstanceIdentifier: !Ref "PrimaryInstanceIdentifier"
      EnablePerformanceInsights: true
      DBParameterGroupName: !Ref "AWS::NoValue"
      Tags:
        - Key: role
          Value: rds-primary
```

Apologies, this is not a standalone example.
