### ISSUE TITLE
RegEx pattern match for E1151 for VpcId doesn't allow {{resolve:ssm:/xxx}}

### ISSUE THREAD

**Issue by webbd-jabil** [aws-cloudformation/cfn-lint#4166]
### CloudFormation Lint Version

1.36.0

### What operating system are you using?

Windows

### Describe the bug

RegEx pattern match for E1151 for VpcId doesn't allow {{resolve:ssm:/xxx}}

I'm storing re-usable values in SSM parameters for use within CloudFormation templates.  Using {{resolve:ssm:/...}} is a valid way to pull the VpcId value.

### Expected behavior

Expression {{resolve:ssm:/xxx}} is allowed

### Reproduction template

```  
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCEndpointEC2:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: 'Interface'
      PrivateDnsEnabled: true
      SubnetIds:
        - "{{resolve:ssm:/Core/Subnet1a}}"
        - "{{resolve:ssm:/Core/Subnet1b}}"
        - "{{resolve:ssm:/Core/Subnet1c}}"
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2
      VpcId: "{{resolve:ssm:/Core/VpcID}}"
```
