### ISSUE TITLE
E3002 Invalid Property Resources/EchoCampaignRDS/Properties/DeletionProtection

### ISSUE THREAD

**Issue by neil-cloudbi** [aws-cloudformation/cfn-lint#474]
0.9.1

This new feature is in the CFN release notes but doesn't seem to be supported in the linter yet:

```
RDS:
   Type: "AWS::RDS::DBInstance"
   Properties:
     DeletionProtection: true
```
