### ISSUE TITLE
Issue with nested functions and mixed invoke formats

### ISSUE THREAD

**Issue by phene** [aws-cloudformation/cfn-lint#545]
*cfn-lint version: 0.9.2

Using a `!Ref` in the second argument of a `!GetAtt` yields an error.

Depending on how I structure it, I can get two different errors:

```yaml
Parameters:
  ProjectS3Root:
    Type: String

  SSMMasterDBUsernameKeyFullName:
    Type: String

  SSMMasterDBPasswordKeyFullName:
    Type: String

  SSMLambdaARN:
    Type: String

  SSMModifiedAt:
    Type: String

  SSMLookup:
    Type: String
    Default: true

  PGMasterUser:
    Type: String
    Default: NONE

  PGMasterPassword:
    Type: String
    Default: NONE

Conditions:
  UseSSM: !Equals [ !Ref SSMLookup, true ]

Resources:

  RDSCredentials:
    Condition: UseSSM
    Type: AWS::CloudFormation::CustomResource
    Version: 1.0
    Properties:
      ServiceToken: !Ref SSMLambdaARN
      SSMKeyList: !Sub ${SSMMasterDBUsernameKeyFullName},${SSMMasterDBPasswordKeyFullName}
      SSMModifiedAt: !Ref SSMModifiedAt

  ############################## Setup Backends ##############################
  Postgres:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "/", [ !Ref ProjectS3Root, "templates/backends/rds.yaml" ] ]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        RdsMasterUsername: !If [ UseSSM, "Fn::GetAtt": [ RDSCredentials, !Ref SSMMasterDBUsernameKeyFullName ], !Ref PGMasterUser ]
        RdsMasterPassword: !If [ UseSSM, "Fn::GetAtt": [ RDSCredentials, !Ref SSMMasterDBPasswordKeyFullName ], !Ref PGMasterPassword ]
```

yields:

```
E0002 Unknown exception while processing rule E1010: sequence item 0: expected string, dict_node found
test-rds.yaml:1:1
```

If I remove the condition, I get a different error:

```yaml
Parameters:
  ProjectS3Root:
    Type: String

  SSMMasterDBUsernameKeyFullName:
    Type: String

  SSMMasterDBPasswordKeyFullName:
    Type: String

  SSMLambdaARN:
    Type: String

  SSMModifiedAt:
    Type: String

Resources:

  RDSCredentials:
    Type: AWS::CloudFormation::CustomResource
    Version: 1.0
    Properties:
      ServiceToken: !Ref SSMLambdaARN
      SSMKeyList: !Sub ${SSMMasterDBUsernameKeyFullName},${SSMMasterDBPasswordKeyFullName}
      SSMModifiedAt: !Ref SSMModifiedAt

  ############################## Setup Backends ##############################
  Postgres:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "/", [ !Ref ProjectS3Root, "templates/backends/rds.yaml" ] ]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        RdsMasterUsername: "Fn::GetAtt": [ RDSCredentials, !Ref SSMMasterDBUsernameKeyFullName ]
        RdsMasterPassword: "Fn::GetAtt": [ RDSCredentials, !Ref SSMMasterDBPasswordKeyFullName ]
```

yields: 

```
E0000 mapping values are not allowed in this context
test-rds.yaml:34:40
```

This, however, works just fine:

```yaml
Parameters:
  ProjectS3Root:
    Type: String

  SSMMasterDBUsernameKeyFullName:
    Type: String

  SSMMasterDBPasswordKeyFullName:
    Type: String

  SSMLambdaARN:
    Type: String

  SSMModifiedAt:
    Type: String

Resources:

  RDSCredentials:
    Type: AWS::CloudFormation::CustomResource
    Version: 1.0
    Properties:
      ServiceToken: !Ref SSMLambdaARN
      SSMKeyList: !Sub ${SSMMasterDBUsernameKeyFullName},${SSMMasterDBPasswordKeyFullName}
      SSMModifiedAt: !Ref SSMModifiedAt

  ############################## Setup Backends ##############################
  Postgres:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "/", [ !Ref ProjectS3Root, "templates/backends/rds.yaml" ] ]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        RdsMasterUsername: !GetAtt [ RDSCredentials, !Ref SSMMasterDBUsernameKeyFullName ]
        RdsMasterPassword: !GetAtt [ RDSCredentials, !Ref SSMMasterDBPasswordKeyFullName ]
```
