### ISSUE TITLE
LoadBalancer doesn't verify SecurityGroups

### ISSUE THREAD

**Issue by viraptor** [aws-cloudformation/cfn-lint#639]
*cfn-lint version: 0.10.3*

*Description of issue.*

`AWS::ElasticLoadBalancingV2::LoadBalancer` doesn't verify that the `SecurityGroups` property lists group ids. This is wrong and will pass:

```
Elb:
  Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
  Properties:
    SecurityGroups:
      - !Ref SecurityGroup
```

This is better (also passes):

```
Elb:
  Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
  Properties:
    SecurityGroups:
      - !GetAtt SecurityGroup.GroupId
```

**Comment by cmmeyer** [comment]
Thanks for the feedback. The problem is, it would be valid to pass in the group IDs as a parameter and reference it the way you do in you first example:

```
Parameters:
  SecurityGroup: 
    Description: Group ID of an existing security group
    Type: String
Resources:
  Elb: 
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties: 
      SecurityGroups: 
      - !Ref SecurityGroup
```

...is perfectly valid.
