### ISSUE TITLE
No obvious way to flag literal embedded parameter syntax as expected (E1029)

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/cfn-lint#740]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.16.0

*Description of issue.*
Fn::Sub style variables in parameter descriptions trigger E1029, however there is no obvious way to suppress this when the use of the ${Something} is intended to be literal, I suspect this may also be the case in other contexts where ${Something} is intended as a literal rather than missing a !Sub / Fn::Sub

To be clear the intent in the original where I encountered this was that the parameter description contain the literal embedded parameter syntax, eg : '${Test1}' and not be expanded.

The sample template below demonstrates the issue, ie Description properties containing literal embedded parameter syntax.

*Sample Template*
```yaml
Description:
    "cfn-lint E1029 false positive"
Parameters:
    Test1:
        Type: String
        Description: "This parameter will replace ${Test1}"
    Test2:
        Type: String
        Description: "This parameter will replace ${!Test2}"

Resources:

    EIP:
        Type: AWS::EC2::EIP
        Properties:
            Domain: vpc

Outputs:
    Test1:
        Value: !Ref Test1
    Test2:
        Value: !Ref Test2
```
