### ISSUE TITLE
Feature Suggestion: Warn instead of error

### ISSUE THREAD

**Issue by AnthonyWC** [aws-cloudformation/cfn-lint#785]
Currently it is possible to setup the tool so that we can arbitrary suppress checking for certain rules.  However I think there are many situations where we prefer to not skip check entirely but also not to fail the linter if the check does not go through.  We want information so user can make a decision based on output.

Most linters has this type of config option, perhaps maybe something like:
```yaml
Metadata:
  cfn-lint:
    config:
      regions:
      - us-east-1
      - us-east-2
      ignore_checks:
      - E2530
      warn_only:
      - W3005
```

With warn, the error findings should still be emitted but exit code should emit a 0 instead of non-zero if only warn rules were triggered.
